'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.services': 'Hizmetler',
    'nav.tours': 'Turlar',
    'nav.about': 'Hakkımızda',
    'nav.blog': 'Blog',
    'nav.contact': 'İletişim',
    
    // Services
    'services.culture-tours': 'Kültür Turları',
    'services.hotel-reservations': 'Otel Rezervasyonları',
    'services.guide-services': 'Rehberlik Hizmetleri',
    'services.adventure-tours': 'Macera Turları',
    
    // Hero Section - Slides
    'hero.slide1.title': 'Eşsiz Türkiye Turları',
    'hero.slide1.description': 'Türkiye\'nin zengin kültürel mirasını keşfedin, unutulmaz anılar biriktirin.',
    'hero.slide2.title': 'Lüks Otel Rezervasyonları',
    'hero.slide2.description': 'Konforlu konaklama seçenekleri ile tatil deneyiminizi mükemmel hale getiriyoruz.',
    'hero.slide3.title': 'Kültür Gezileri ve Rehberlik',
    'hero.slide3.description': 'Uzman rehberlerimiz eşliğinde tarihi ve kültürel zenginlikleri keşfedin.',
    'hero.slide4.title': 'Özel Tatil Paketleri',
    'hero.slide4.description': 'Size özel hazırladığımız tatil paketleri ile hayalinizdeki seyahati yaşayın.',
    'hero.cta.tours': 'Turlarımız',
    'hero.cta.hotels': 'Oteller',
    'hero.cta.culture': 'Kültür Turları',
    'hero.cta.packages': 'Paketler',
    'hero.cta.services': 'Hizmetlerimiz',
    'hero.video.title': 'Keşif Videosu',
    'hero.scroll.text': 'Kaydır',
    
    // Hero highlights for text styling
    'hero.highlight.memories': 'unutulmaz anılar biriktirin',
    'hero.highlight.perfect': 'mükemmel hale getiriyoruz',
    'hero.highlight.discover': 'zenginlikleri keşfedin',
    'hero.highlight.travel': 'seyahati yaşayın',
    'hero.video.coming-soon': 'Tanıtım videosu yakında...',
    
    // Services Section
    'services.title': 'Hizmet',
    'services.title.highlight': 'Alanlarımız',
    'services.description': '15 yıllık deneyimimizle turizm, seyahat ve rehberlik alanlarında kapsamlı hizmetler sunuyoruz.',
    'services.view-details': 'Detayları İncele',
    'services.cta.title': 'Hayalinizdeki Tur İçin Teklif Alın',
    'services.cta.description': 'Uzman ekibimizle seyahat planınızı değerlendirin ve size özel turlar keşfedin.',
    'services.cta.button': 'Ücretsiz Danışmanlık',
    
    // Tours Section
    'tours.title': 'Öne Çıkan',
    'tours.title.highlight': 'Turlar',
    'tours.description': 'En popüler destinasyonlarımızı keşfedin ve unutulmaz anılar biriktirin.',
    'tours.view-all': 'Tüm Turları Gör',
    'tours.duration': 'gün',
    'tours.from': 'başlangıç',
    
    // About Section
    'about.title': 'Hakkımızda',
    'about.description': 'Türkiye\'nin güzelliklerini dünyaya tanıtan, 15 yıllık deneyimi ile turizm sektöründe öncü bir şirketiz.',
    
    // About Hero Section
    'about.hero.title.turkey': 'Türkiye\'nin',
    'about.hero.title.discovery': 'Güzelliklerini',
    'about.hero.title.invite': 'Keşfedin',
    'about.hero.description': '15+ yıldır kültür turizmi, rehberlik ve otel rezervasyon hizmetlerinde unutulmaz deneyimler sunan profesyonel ekibiz.',
    'about.hero.cta.story': 'Hikayemizi Keşfedin',
    'about.hero.cta.video': 'Tanıtım Videosu',
    'about.hero.stats.guests': 'Mutlu Konuk',
    'about.hero.stats.experience': 'Yıllık Deneyim',
    'about.hero.stats.tours': 'Tamamlanan Tur',
    'about.hero.badge.experience': '15+ Yıllık Deneyim',
    'about.hero.video.title': 'Parla Travel Tanıtım Videosu',
    'about.hero.alt.turkey': 'Güzel Türkiye Manzarası',
    'about.hero.alt.istanbul': 'İstanbul Turizmi',
    'about.hero.alt.culture': 'Türk Kültürü',
    'about.hero.alt.travel': 'Seyahat Deneyimi',
    'about.hero.alt.destinations': 'Güzel Destinasyonlar',

    // Company Story Section
    'about.story.title': 'Hikayemiz',
    'about.story.description': '2008\'den beri Türk turizmini yönlendiren bir yolculuk. Her adımda kalite, güven ve misafir memnuniyeti odaklı büyüdük.',
    'about.story.foundation.year': '2008',
    'about.story.foundation.title': 'Turizm Yolculuğumuzun Başlangıcı',
    'about.story.foundation.description': 'İstanbul\'da profesyonel turizm rehberliğinde ilk adımlarımızı attık. Vizyonumuz, Türkiye\'nin kültürel zenginliklerini dünyaya tanıtmak ve unutulmaz seyahat deneyimleri yaratmaktı.',
    'about.story.foundation.stat1.label': 'İlk Tur',
    'about.story.foundation.stat1.value': 'İstanbul',
    'about.story.foundation.stat2.label': 'Ekip Büyüklüğü',
    'about.story.foundation.stat2.value': '5 Kişi',
    'about.story.expansion.year': '2015',
    'about.story.expansion.title': 'Hizmet Çeşitliliği',
    'about.story.expansion.description': 'Ekibimizi genişlettik ve hizmet portföyümüze otel rezervasyonları ile kültür turları ekledik. Türkiye genelinde rehberlik hizmetleri vermeye başladık.',
    'about.story.expansion.stat1.label': 'Tur Destinasyonları',
    'about.story.expansion.stat1.value': '25+',
    'about.story.expansion.stat2.label': 'Ekip Büyüklüğü',
    'about.story.expansion.stat2.value': '20 Kişi',
    'about.story.innovation.year': '2020',
    'about.story.innovation.title': 'Dijital Dönüşüm',
    'about.story.innovation.description': 'Dijital teknolojileri benimsedik, online rezervasyon sistemi ve mobil rehberlik uygulamaları geliştirerek müşteri deneyimini dijitalleştirdik.',
    'about.story.innovation.stat1.label': 'Online Rezervasyonlar',
    'about.story.innovation.stat1.value': '%85',
    'about.story.innovation.stat2.label': 'Mobil Uygulama İndirmeleri',
    'about.story.innovation.stat2.value': '10K+',
    'about.story.leadership.year': '2024',
    'about.story.leadership.title': 'Turizm Sektöründe Liderlik',
    'about.story.leadership.description': 'Bugün Türk turizminin en güvenilir markalarından biriyiz ve sürdürülebilir turizm anlayışımızla geleceğin seyahat deneyimlerini şekillendirmeye devam ediyoruz.',
    'about.story.leadership.stat1.label': 'Yıllık Konuk',
    'about.story.leadership.stat1.value': '5000+',
    'about.story.leadership.stat2.label': 'Ekip Büyüklüğü',
    'about.story.leadership.stat2.value': '45 Kişi',
    'about.story.mission.title': 'Misyonumuz',
    'about.story.mission.description': 'Türkiye\'nin eşsiz güzelliklerini, zengin kültürünü ve tarihini tüm dünyaya tanıtarak unutulmaz seyahat deneyimleri sunmak. Her turda kalite, güven ve profesyonellik ilkelerini benimseyerek, misafirlerimizin hayallerindeki tatili gerçeğe dönüştürüyoruz.',

    // Company Values Section
    'about.values.title': 'Değerlerimiz',
    'about.values.description': 'Parla Travel olarak, her turda bizi yönlendiren temel değerlerimiz, turizm sektöründe bizi farklı kılan ve misafirlerimizin güvenini kazandıran ilkelerimizdir.',
    'about.values.quality.title': 'Kaliteli Hizmet',
    'about.values.quality.description': 'Her turda en yüksek hizmet kalitesini sunuyor, misafirlerimizin memnuniyetini ön planda tutuyoruz.',
    'about.values.trust.title': 'Güvenilirlik',
    'about.values.trust.description': 'Misafirlerimizle uzun vadeli güven ilişkileri kuruyoruz ve verdiğimiz sözü tam olarak yerine getiriyoruz.',
    'about.values.innovation.title': 'İnovasyon',
    'about.values.innovation.description': 'Turizm trendlerini takip ediyor, teknoloji destekli çözümlerle seyahat deneyimlerini geliştiriyoruz.',
    'about.values.teamwork.title': 'Takım Ruhu',
    'about.values.teamwork.description': 'Profesyonel ekibimizle birlikte çalışıyor, unutulmaz anıları hep birlikte yaratıyoruz.',
    'about.values.sustainability.title': 'Sürdürülebilir Turizm',
    'about.values.sustainability.description': 'Çevre dostu turizm anlayışımızla yerel kültürleri koruyoruz, gelecek nesillere yaşanabilir bir dünya bırakıyoruz.',
    'about.values.passion.title': 'Tutku ve Adanmışlık',
    'about.values.passion.description': 'Turizm işini tutkuyla yapıyoruz ve her seyahate kalbimizi koyuyoruz.',
    'about.values.culture.title': 'Kurumsal Kültürümüz',
    'about.values.culture.description': 'Parla Travel\'da her birey değerlidir. Açık iletişim, sürekli öğrenme ve gelişime odaklanan kültürümüzle ekip üyelerimizin potansiyellerini en üst düzeye çıkarıyoruz. Birlikte büyüyor, birlikte başarıyoruz.',
    'about.values.culture.stat1.value': '45+',
    'about.values.culture.stat1.label': 'Ekip Üyesi',
    'about.values.culture.stat2.value': '%98',
    'about.values.culture.stat2.label': 'Misafir Memnuniyeti',
    'about.values.culture.stat3.value': '7.5',
    'about.values.culture.stat3.label': 'Ortalama Çalışma Süresi (Yıl)',

    // Company Stats Section
    'about.stats.title.main': 'Parla Travel',
    'about.stats.title.highlight': 'Rakamlarla',
    'about.stats.description': '15+ yıllık deneyimimiz ve başarılarımızla Türk turizmini yönlendiren güçlü bir ekibiz.',
    'about.stats.cultural.value': '220',
    'about.stats.cultural.label': 'Kültür Turu',
    'about.stats.special.value': '180',
    'about.stats.special.label': 'Özel Tur',
    'about.stats.guide.value': '150',
    'about.stats.guide.label': 'Rehberlik Hizmeti',
    'about.stats.suffix.tours': 'Tur',
    'about.stats.conclusion': 'Her turda kalite, güven ve profesyonelliği birleştirerek müşterilerimizin seyahat hayallerini gerçeğe dönüştürüyor, unutulmaz anılar yaratıyoruz.',
    
    // Contact Section
    'contact.title': 'İletişim',
    'contact.get-in-touch': 'Bizimle İletişime Geçin',
    'contact.description': 'Sorularınız için bize ulaşın, size en iyi hizmeti sunmak için buradayız.',
    
    // Contact Hero Section
    'contact.hero.title.main': 'İletişime',
    'contact.hero.title.highlight': 'Geçin',
    'contact.hero.description': 'Seyahat planlarınız için bilgi almak, rezervasyon yapmak veya özel tur talepleri için',
    'contact.hero.description.highlight': ' bizimle iletişime geçin',
    'contact.hero.stats.service.value': '24/7',
    'contact.hero.stats.service.label': 'Rezervasyon Hizmetleri',
    'contact.hero.stats.response.value': '<1',
    'contact.hero.stats.response.label': 'Saat İçinde Yanıt',
    
    // Contact Info Cards
    'contact.info.phone.title': 'Telefon',
    'contact.info.phone.number': '+90 212 555 0123',
    'contact.info.phone.hours': 'Pazartesi - Cuma: 09:00 - 18:00',
    'contact.info.email.title': 'E-posta',
    'contact.info.email.address': 'info@parlatravel.com',
    'contact.info.email.support': '7/24 e-posta desteği',
    'contact.info.address.title': 'Adres',
    'contact.info.address.street': 'Maslak Mahallesi, Büyükdere Cad.',
    'contact.info.address.details': 'No:123 Sarıyer/İstanbul',
    'contact.info.hours.title': 'Çalışma Saatleri',
    'contact.info.hours.weekdays': 'Pazartesi - Cuma: 09:00 - 18:00',
    'contact.info.hours.saturday': 'Cumartesi: 09:00 - 14:00',
    
    // Contact Form Section
    'contact.form.title': 'Seyahat Talebi Oluşturun',
    'contact.form.description': 'Unutulmaz bir seyahat deneyimi için aşağıdaki formu doldurun.',
    'contact.form.description.support': 'Uzman ekibimiz 24 saat içinde sizinle iletişime geçerek kişiselleştirilmiş seyahat planınızı hazırlayacak.',
    
    // Form Fields
    'contact.form.name.label': 'Ad Soyad',
    'contact.form.name.placeholder': 'Adınız Soyadınız',
    'contact.form.email.label': 'E-posta',
    'contact.form.email.placeholder': 'ornek@email.com',
    'contact.form.phone.label': 'Telefon',
    'contact.form.phone.placeholder': '+90 5XX XXX XX XX',
    'contact.form.company.label': 'Şirket/Kurum',
    'contact.form.company.placeholder': 'Şirket Adı',
    'contact.form.service.label': 'Hizmet Türü',
    'contact.form.service.placeholder': 'Hizmet seçiniz',
    'contact.form.service.cultural-tours': 'Kültür Turları',
    'contact.form.service.custom-tours': 'Özel Tur Organizasyonu',
    'contact.form.service.hotel-reservation': 'Otel Rezervasyonu',
    'contact.form.service.group-tours': 'Grup Turları',
    'contact.form.service.guide-services': 'Profesyonel Rehberlik',
    'contact.form.service.other': 'Diğer',
    'contact.form.budget.label': 'Bütçe Aralığı',
    'contact.form.budget.placeholder': 'Bütçe seçiniz',
    'contact.form.budget.5k-15k': '5.000 - 15.000 TL',
    'contact.form.budget.15k-30k': '15.000 - 30.000 TL',
    'contact.form.budget.30k-50k': '30.000 - 50.000 TL',
    'contact.form.budget.50k+': '50.000 TL+',
    'contact.form.timeline.label': 'Seyahat Zamanı',
    'contact.form.timeline.placeholder': 'Zaman seçiniz',
    'contact.form.timeline.asap': 'En kısa sürede',
    'contact.form.timeline.1-month': '1 ay içinde',
    'contact.form.timeline.3-months': '3 ay içinde',
    'contact.form.timeline.6-months': '6 ay içinde',
    'contact.form.timeline.flexible': 'Esnek',
    'contact.form.message.label': 'Seyahat Detayları',
    'contact.form.message.placeholder': 'Seyahat planınızın detaylarını, gitmek istediğiniz yerleri, özel taleplerinizi ve beklentilerinizi açıklayın...',
    'contact.form.consent.text': 'KVKK kapsamında kişisel verilerimin işlenmesini ve tarafımla iletişime geçilmesini kabul ediyorum.',
    'contact.form.submit.text': 'Seyahat Talebini Gönder',
    
    // Form Process Info
    'contact.form.process.title': 'Form Gönderildikten Sonra',
    'contact.form.process.step1.title': 'Onay E-postası',
    'contact.form.process.step1.description': 'Talebiniz alındı mesajı anında e-postanıza gelir',
    'contact.form.process.step2.title': 'İlk İletişim',
    'contact.form.process.step2.description': '24 saat içinde uzman ekibimiz sizinle görüşür',
    'contact.form.process.step3.title': 'Detaylı Teklif',
    'contact.form.process.step3.description': '3-5 gün içinde kapsamlı teklifimizi sunarız',
    
    // Quick Contact
    'contact.form.quick.title': 'Hızlı İletişim',
    'contact.form.quick.description': 'Acil durumlar için doğrudan aramayı tercih ediyorsanız:',
    'contact.form.quick.phone': '+90 212 555 0123',
    'contact.form.quick.email': 'info@parlatravel.com',
    
    // Contact Page Metadata
    'contact.meta.title': 'İletişim | Parla Travel',
    'contact.meta.description': 'Parla Travel ile iletişime geçin. Tur rezervasyonunuz için teklif alın ve uzman ekibimizle görüşün.',
    
    // Footer
    'footer.company.description': 'Turizm ve seyahat alanlarında 15+ yıllık deneyimle, Türkiye\'nin en güzel destinasyonlarını keşfetmeniz için unutulmaz turlar düzenliyoruz.',
    'footer.services.title': 'Hizmetlerimiz',
    'footer.services.culture-tours': 'Kültür Turları',
    'footer.services.hotel-reservations': 'Otel Rezervasyonları',
    'footer.services.guide-services': 'Rehberlik Hizmetleri',
    'footer.services.adventure-tours': 'Macera Turları',
    'footer.quick-links.title': 'Hızlı Linkler',
    'footer.quick-links.about': 'Hakkımızda',
    'footer.quick-links.tours': 'Turlarımız',
    'footer.quick-links.blog': 'Blog',
    'footer.quick-links.career': 'Kariyer',
    'footer.quick-links.contact': 'İletişim',
    'footer.social.facebook': 'Facebook',
    'footer.social.instagram': 'Instagram',
    'footer.social.linkedin': 'LinkedIn',
    'footer.social.twitter': 'Twitter',
    'footer.copyright': 'Parla Travel. Tüm hakları saklıdır.',
    'footer.privacy-policy': 'Gizlilik Politikası',
    'footer.terms-of-service': 'Kullanım Koşulları',
    'footer.developed-by': 'Designed & Developed by',
    'footer.description': 'Türkiye\'nin en güzel yerlerini keşfetmeniz için profesyonel turizm hizmetleri sunuyoruz.',
    'footer.quick-links': 'Hızlı Linkler',
    'footer.services': 'Hizmetlerimiz',
    'footer.contact-info': 'İletişim Bilgileri',
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.address.street': 'Taksim Meydanı, İstiklal Caddesi',
    'footer.address.details': 'No: 250, Beyoğlu/İstanbul',
    
    // Company Stats
    'stats.years': 'Yıllık Deneyim',
    'stats.tours': 'Tamamlanan Tur',
    'stats.customers': 'Mutlu Müşteri',
    'stats.destinations': 'Destinasyon',
    
    // Service Details
    'services.culture-tours.description': 'Türkiye\'nin zengin tarihî ve kültürel mirasını keşfedin, uzman rehberlerimiz eşliğinde unutulmaz deneyimler yaşayın.',
    'services.culture-tours.features': 'Tarihî Mekanlar, Müze Gezileri, Antik Şehirler, Yerel Kültür',
    'services.culture-tours.process': '1-15 Gün',
    'services.hotel-reservations.description': 'Konforlu konaklama deneyimi için en iyi otellerde rezervasyon hizmeti sunuyoruz, her bütçeye uygun seçenekler.',
    'services.hotel-reservations.features': 'Lüks Oteller, Boutique Hotels, Butik Pansiyonlar, Özel Villalar',
    'services.hotel-reservations.process': '1-7 Gün',
    'services.guide-services.description': 'Profesyonel ve deneyimli rehberlerimiz ile Türkiye\'nin her köşesini keşfedin, kişisel ve grup turları.',
    'services.guide-services.features': 'Kişisel Rehberlik, Grup Rehberliği, Çok Dilli Hizmet, Özel İlgi Alanları',
    'services.guide-services.process': '1-30 Gün',
    'services.adventure-tours.description': 'Size özel hazırladığımız tatil paketleri ile hayalinizdeki seyahati yaşayın, tamamen kişiselleştirilebilir.',
    'services.adventure-tours.features': 'VIP Turlar, Romantik Geziler, Macera Turları, Gastronomi Turları',
    'services.adventure-tours.process': '3-21 Gün',

    // Featured Tours Section
    'featured-tours.title': 'Öne Çıkan',
    'featured-tours.title.highlight': 'Turlarımız',
    'featured-tours.description': 'En popüler destinasyonlarımızda unutulmaz deneyimler yaşayın. Uzman rehberlerimiz eşliğinde Türkiye\'nin en güzel yerlerini keşfedin.',
    'featured-tours.filter.all': 'Tümü',
    'featured-tours.filter.cultural': 'Kültürel',
    'featured-tours.filter.natural': 'Doğal',
    'featured-tours.filter.adventure': 'Macera',
    'featured-tours.category.cultural': 'Kültürel',
    'featured-tours.category.natural': 'Doğal',
    'featured-tours.category.adventure': 'Macera',
    'featured-tours.category.general': 'Genel',
    'featured-tours.view-details': 'Detayları Görüntüle',
    'featured-tours.explore': 'İncele',
    'featured-tours.tour-duration': 'Tur Süresi',
    'featured-tours.cta.description': 'Daha fazla tur seçeneği için tam listemize göz atın.',
    'featured-tours.view-all': 'Tüm Turları Görüntüle',

    // Services Preview Section
    'services-preview.badge': 'Uzman Hizmetlerimiz',
    'services-preview.title.main': 'Türkiye\'yi',
    'services-preview.title.highlight': 'Keşfediyoruz',
    'services-preview.description': '15+ yıllık deneyimimizle turizm ve seyahat alanlarında',
    'services-preview.description.highlight': ' unutulmaz deneyimler',
    'services-preview.description.end': ' sunuyoruz.',
    'services-preview.stats.tours': 'Gerçekleştirilen Tur',
    'services-preview.stats.experience': 'Yıllık Deneyim',
    'services-preview.stats.visitors': 'Mutlu Ziyaretçi',
    
    // Service Cards
    'services-preview.service.culture-tours.title': 'Kültür Turları',
    'services-preview.service.culture-tours.short': 'Tarih ve kültür keşfi',
    'services-preview.service.culture-tours.description': 'Türkiye\'nin zengin tarihî ve kültürel mirasını keşfedin. Uzman rehberlerimiz eşliğinde unutulmaz deneyimler yaşayın.',
    'services-preview.service.culture-tours.feature1': 'Tarihî Mekanlar',
    'services-preview.service.culture-tours.feature2': 'Müze Gezileri',
    'services-preview.service.culture-tours.feature3': 'Yerel Kültür',
    
    'services-preview.service.hotel-reservations.title': 'Otel Rezervasyonları',
    'services-preview.service.hotel-reservations.short': 'Kaliteli konaklama çözümleri',
    'services-preview.service.hotel-reservations.description': 'Konforlu konaklama deneyimi için en iyi otellerde rezervasyon hizmeti sunuyoruz. Her bütçeye uygun seçenekler mevcuttur.',
    'services-preview.service.hotel-reservations.feature1': 'Lüks Oteller',
    'services-preview.service.hotel-reservations.feature2': 'Boutique Hotels',
    'services-preview.service.hotel-reservations.feature3': 'Ekonomik Seçenekler',
    
    'services-preview.service.guide-services.title': 'Rehberlik Hizmetleri',
    'services-preview.service.guide-services.short': 'Uzman rehberlik desteği',
    'services-preview.service.guide-services.description': 'Profesyonel ve deneyimli rehberlerimiz ile Türkiye\'nin her köşesini keşfedin. Kişisel ve grup turları için özel hizmet.',
    'services-preview.service.guide-services.feature1': 'Kişisel Rehberlik',
    'services-preview.service.guide-services.feature2': 'Grup Turları',
    'services-preview.service.guide-services.feature3': 'Dil Desteği',
    
    'services-preview.tour-label': 'Tur',
    'services-preview.premium-label': 'Premium',
    'services-preview.guarantee-label': 'Garanti',
    'services-preview.button.explore': 'Detayları Keşfedin',

    // Services Hero
    'services-hero.professional': 'Profesyonel',
    'services-hero.services': 'Hizmetlerimiz',
    'services-hero.description': 'Kültür turlarından otel rezervasyonlarına, rehberlik hizmetlerinden özel turlara kadar geniş bir yelpazede hizmet sunuyoruz,',
    'services-hero.description.highlight': 'unutulmaz deneyimler yaşatıyoruz',
    'services-hero.stats.tours': 'Düzenlenen Tur',
    'services-hero.stats.visitors': 'Mutlu Ziyaretçi',
    'services-hero.established': 'EST. 2008',

    // Service Process
    'service-process.title': 'Çalışma',
    'service-process.title.highlight': 'Sürecimiz',
    'service-process.description': 'Her turda sistematik bir yaklaşım benimsiyor, unutulmaz deneyimler için dört aşamalı süreç takip ediyoruz.',
    'service-process.step1.title': 'Danışmanlık & Planlama',
    'service-process.step1.description': 'Seyahat ihtiyaçlarınızı detaylı olarak analiz ediyor, kişiye özel planlamalar yapıyoruz.',
    'service-process.step1.duration': '1-3 Gün',
    'service-process.step1.details': 'Seyahat tercihlerinizin analizi, Bütçe planlaması ve öneri paketleri, Tarih ve süre planlaması, Özel isteklerinizin değerlendirilmesi',
    'service-process.step2.title': 'Program & Rota Tasarımı',
    'service-process.step2.description': 'Uzman ekibimizle size özel tur programları geliştiriyor, benzersiz deneyimler tasarlıyoruz.',
    'service-process.step2.duration': '2-5 Gün',
    'service-process.step2.details': 'Özel rota ve program hazırlığı, Destinasyon seçimi ve aktivite planı, Revizyon ve optimizasyon süreci, Nihai program onayı ve detaylandırma',
    'service-process.step3.title': 'Rezervasyon & Organizasyon',
    'service-process.step3.description': 'Profesyonel rezervasyon hizmetleriyle turunuzun tüm detaylarını organize ediyor, sorunsuz seyahatler sağlıyoruz.',
    'service-process.step3.duration': '3-7 Gün',
    'service-process.step3.details': 'Otel ve konaklama rezervasyonları, Ulaşım ve transfer organizasyonu, Aktivite ve tur rezervasyonları, Sigorta ve yasal süreç takibi',
    'service-process.step4.title': 'Rehberlik & Hizmet',
    'service-process.step4.description': 'Profesyonel rehberlik hizmetiyle turunuzu gerçekleştiriyor ve mükemmel deneyimler sunuyoruz.',
    'service-process.step4.duration': '1-30 Gün',
    'service-process.step4.details': 'Uzman rehber eşliğinde tur gerçekleştirme, 7/24 destek ve yardım hattı, Anlık problemlerin çözümü, Tur sonrası memnuniyet takibi',
    'service-process.in-this-step': 'Bu Aşamada:',
    'service-process.step': 'Adım',
    'service-process.preparation': 'Tur Hazırlık Süreci',
    'service-process.estimated-time': 'Tahmini Süre',
    'service-process.previous-step': 'Önceki Adım',
    'service-process.next-step': 'Sonraki Adım',

    // Services CTA
    'services-cta.title': 'Seyahatinizi Birlikte',
    'services-cta.title.highlight': 'Planlayalım',
    'services-cta.description': '15 yıllık deneyimimiz ve uzman ekibimizle seyahatinizi en iyi şekilde organize ediyoruz.',
    'services-cta.description.highlight': 'Unutulmaz deneyimler yaşatıyoruz',
    'services-cta.contact.phone': 'Telefon',
    'services-cta.contact.phone.number': '+90 212 555 0156',
    'services-cta.contact.email': 'E-posta',
    'services-cta.contact.email.address': 'info@parlagroup.com',
    'services-cta.contact.address': 'Adres',
    'services-cta.contact.address.location': 'Taksim, İstanbul',
    'services-cta.cta.get-prices': 'Tur Fiyatları Al',
    'services-cta.cta.call-now': 'Hemen Ara',
    'services-cta.testimonials.title': 'Müşteri',
    'services-cta.testimonials.title.highlight': 'Yorumları',
    'services-cta.testimonial1.name': 'Mehmet Demir',
    'services-cta.testimonial1.company': 'Ankara',
    'services-cta.testimonial1.comment': 'Parla Travel ile Kapadokya turumuza katıldık. Profesyonel rehberlik hizmetleri ve mükemmel organizasyon ile unutulmaz bir deneyim yaşadık.',
    'services-cta.testimonial2.name': 'Ayşe Çelik',
    'services-cta.testimonial2.company': 'İzmir',
    'services-cta.testimonial2.comment': 'İstanbul kültür turumuzda gösterdikleri özen ve bilgi birikimi gerçekten takdire şayan. Her detay düşünülmüş, harika bir seyahatti.',
    'services-cta.stats.tours': 'Düzenlenen Tur',
    'services-cta.stats.visitors': 'Mutlu Ziyaretçi',
    'services-cta.support.title': '24/7 Müşteri Desteği',
    'services-cta.support.description': 'Seyahatinizle ilgili her konuda size destek olmaya hazırız.',

    // Common
    'common.read-more': 'Devamını Oku',
    'common.learn-more': 'Daha Fazla Bilgi',
    'common.book-now': 'Hemen Rezervasyon Yap',
    'common.get-quote': 'Teklif Al',
    'common.view-details': 'Detayları İncele',

    // Tours Page
    // Tours Hero Section
    'tours-page.hero.breadcrumb.home': 'Ana Sayfa',
    'tours-page.hero.breadcrumb.tours': 'Turlarımız',
    'tours-page.hero.title.popular': 'Popüler',
    'tours-page.hero.title.tours': 'Turlarımız',
    'tours-page.hero.description.main': '650\'den fazla başarılı tur deneyimimizle kültür gezilerinden doğa turlarına kadar geniş bir portföy sunuyoruz,',
    'tours-page.hero.description.highlight': 'unutulmaz anılar yaratıyoruz',
    'tours-page.hero.category.cultural-tours': 'Kültür Turları',
    'tours-page.hero.category.cultural-tours.count': '220+ Tur',
    'tours-page.hero.category.guide-services': 'Rehberlik',
    'tours-page.hero.category.guide-services.count': '150+ Tur',
    'tours-page.hero.category.special-tours': 'Özel Turlar',
    'tours-page.hero.category.special-tours.count': '100+ Tur',
    'tours-page.hero.established': 'EST. 2008',

    // Tours Filter Section
    'tours-page.filter.all': 'Tümü',
    'tours-page.filter.cultural': 'Kültür Turları',
    'tours-page.filter.nature': 'Doğa Turları',
    'tours-page.filter.adventure': 'Macera Turları',
    'tours-page.filter.city': 'Şehir Turları',

    // Tours Grid Section
    'tours-page.grid.category.all': 'Tüm Turlar',
    'tours-page.grid.category.cultural': 'Kültür Turları',
    'tours-page.grid.category.nature': 'Doğa Turları',
    'tours-page.grid.category.adventure': 'Macera Turları',
    'tours-page.grid.category.city': 'Şehir Turları',
    'tours-page.grid.category.tours': 'Turlar',
    'tours-page.grid.tours-found': 'tur bulundu',
    'tours-page.grid.view-tour': 'Turu İncele',
    'tours-page.grid.tour-details': 'Tur Detayları',
    'tours-page.grid.load-more': 'Daha Fazla Tur',

    // Tours Data
    'tours-page.tour.istanbul-culture.title': 'İstanbul Kültür Turu',
    'tours-page.tour.istanbul-culture.category': 'Kültür Turları',
    'tours-page.tour.istanbul-culture.location': 'İstanbul, Türkiye',
    'tours-page.tour.istanbul-culture.description': 'Tarihi Sultanahmet\'ten modern Beyoğlu\'na kadar İstanbul\'un tüm güzelliklerini keşfediyoruz.',
    'tours-page.tour.cappadocia-balloon.title': 'Kapadokya Balon Turu',
    'tours-page.tour.cappadocia-balloon.category': 'Macera Turları',
    'tours-page.tour.cappadocia-balloon.location': 'Kapadokya, Nevşehir',
    'tours-page.tour.cappadocia-balloon.description': 'Kapadokya\'nın eşsiz peyzajını sıcak hava balon turu ile keşfetmenin unutulmaz deneyimi.',
    'tours-page.tour.pamukkale-nature.title': 'Pamukkale Doğa Turu',
    'tours-page.tour.pamukkale-nature.category': 'Doğa Turları',
    'tours-page.tour.pamukkale-nature.location': 'Pamukkale, Denizli',
    'tours-page.tour.pamukkale-nature.description': 'Beyaz travertenler ve antik Hierapolis kalıntıları ile doğa harikası Pamukkale keşfi.',
    'tours-page.tour.antalya-city.title': 'Antalya Şehir Turu',
    'tours-page.tour.antalya-city.category': 'Şehir Turları',
    'tours-page.tour.antalya-city.location': 'Antalya, Türkiye',
    'tours-page.tour.antalya-city.description': 'Akdeniz\'in turkuaz suları ve tarihi Kaleiçi ile Antalya\'nın eşsiz güzelliklerini yaşayın.',
    'tours-page.tour.ephesus-ancient.title': 'Efes Antik Kenti Turu',
    'tours-page.tour.ephesus-ancient.category': 'Kültür Turları',
    'tours-page.tour.ephesus-ancient.location': 'Efes, İzmir',
    'tours-page.tour.ephesus-ancient.description': 'Antik dünyanın en iyi korunmuş şehirlerinden Efes\'in tarihî atmosferinde yolculuk.',
    'tours-page.tour.blacksea-highlands.title': 'Karadeniz Yaylalar Turu',
    'tours-page.tour.blacksea-highlands.category': 'Doğa Turları',
    'tours-page.tour.blacksea-highlands.location': 'Karadeniz Bölgesi',
    'tours-page.tour.blacksea-highlands.description': 'Karadeniz\'in yemyeşil yaylaları ve doğal güzellikleri ile huzurlu bir kaçış deneyimi.',

    // Tours CTA Section
    'tours-page.cta.title.main': 'Hayalinizdeki Seyahati',
    'tours-page.cta.title.highlight': 'Birlikte Planlayalım',
    'tours-page.cta.description.main': '650\'den fazla başarılı tur deneyimimizle sizin de hayalinizdeki seyahati gerçekleştirebiliriz.',
    'tours-page.cta.description.highlight': 'Unutulmaz anılar yaratıyoruz',
    'tours-page.cta.button.plan-trip': 'Seyahatinizi Planlayın',
    'tours-page.cta.button.download-catalog': 'Tur Kataloğu İndir',
    'tours-page.cta.button.share': 'Paylaş',
    'tours-page.cta.stats.tours.number': '650+',
    'tours-page.cta.stats.tours.label': 'Düzenlenen Tur',
    'tours-page.cta.stats.experience.number': '15+',
    'tours-page.cta.stats.experience.label': 'Yıl Deneyim',
    'tours-page.cta.stats.visitors.number': '12000+',
    'tours-page.cta.stats.visitors.label': 'Mutlu Ziyaretçi',
    'tours-page.cta.stats.destinations.number': '45+',
    'tours-page.cta.stats.destinations.label': 'Destinasyon',

    // Tours Page Metadata
    'tours-page.meta.title': 'Türkiye Turları - Popüler Destinasyonlar | Parla Travel',
    'tours-page.meta.description': 'Kültür turlarından doğa gezilerine, macera turlarından şehir turlarına kadar geniş portföyümüzde Türkiye\'nin en güzel destinasyonlarını keşfedin.',

    // Blog Page
    // Blog Hero Section
    'blog.hero.title.main': 'Blog &',
    'blog.hero.title.highlight': 'Haberler',
    'blog.hero.description.main': 'Seyahat, turizm ve keşif dünyasındaki güncel gelişmeleri takip edin.',
    'blog.hero.description.highlight': 'Uzman rehber önerilerimizi keşfedin',
    'blog.hero.stats.posts.value': '150+',
    'blog.hero.stats.posts.label': 'Blog Yazısı',
    'blog.hero.stats.readers.value': '25K+',
    'blog.hero.stats.readers.label': 'Okuyucu',
    'blog.hero.stats.categories.value': '15+',
    'blog.hero.stats.categories.label': 'Kategori',
    'blog.hero.featured.alt': '2024 Seyahat Trendleri ve Destinasyon Rehberi',
    'blog.hero.featured.badge': 'Öne Çıkan',
    'blog.hero.featured.title': '2024 Seyahat Trendleri ve Destinasyon Rehberi',
    'blog.hero.featured.description': '2024 yılının en popüler destinasyonları ve seyahat trendleri hakkında uzman rehberlerimizin detaylı analizi ve önerileri.',
    'blog.hero.featured.date': '15 Mayıs 2024',
    'blog.hero.featured.author': 'Mehmet Seyhan',
    'blog.hero.featured.views': '1.2K',
    'blog.hero.featured.read-more': 'Devamını Oku',

    // Blog Categories
    'blog.categories.title': 'Blog Kategorileri',
    'blog.categories.description': 'İlgi alanınıza göre içerikleri keşfedin ve sektördeki gelişmeleri takip edin.',
    'blog.categories.all.name': 'Tümü',
    'blog.categories.all.description': 'Tüm blog yazıları',
    'blog.categories.destinations.name': 'Destinasyonlar',
    'blog.categories.destinations.description': 'Popüler seyahat destinasyonları ve rehberler',
    'blog.categories.travel-guides.name': 'Seyahat Rehberleri',
    'blog.categories.travel-guides.description': 'Detaylı gezi planları ve öneriler',
    'blog.categories.accommodation.name': 'Konaklama',
    'blog.categories.accommodation.description': 'Otel önerileri ve konaklama rehberleri',
    'blog.categories.gastronomy.name': 'Gastronomi',
    'blog.categories.gastronomy.description': 'Yerel lezzetler ve kulinarya deneyimleri',
    'blog.categories.team.name': 'Ekip & Kariyer',
    'blog.categories.team.description': 'Ekip hikayeleri ve turizm kariyeri',
    'blog.categories.photography.name': 'Seyahat Fotoğrafçılığı',
    'blog.categories.photography.description': 'Fotoğraf ipuçları ve en güzel kareler',
    'blog.categories.awards.name': 'Ödüller & Başarılar',
    'blog.categories.awards.description': 'Aldığımız ödüller ve başarı hikayeleri',
    'blog.categories.selected': 'Seçili kategori',
    'blog.categories.posts': 'yazı',

    // Blog Grid
    'blog.grid.title.all': 'Son Blog Yazıları',
    'blog.grid.title.filtered': 'Filtrelenmiş Yazılar',
    'blog.grid.no-posts': 'Bu kategoride henüz yazı bulunmuyor.',
    'blog.grid.posts-found': 'yazı bulundu',
    'blog.grid.featured': 'Öne Çıkan',
    'blog.grid.read-more': 'Devamını Oku',
    'blog.grid.load-more': 'Daha Fazla Yükle',

    // Blog Post Categories
    'blog.posts.category.travel-guide': 'Seyahat Rehberi',
    'blog.posts.category.destination': 'Destinasyon',
    'blog.posts.category.city-tours': 'Şehir Turları',
    'blog.posts.category.accommodation': 'Konaklama',
    'blog.posts.category.gastronomy': 'Gastronomi',
    'blog.posts.category.blue-tour': 'Mavi Tur',
    'blog.posts.category.team': 'Ekip & Kariyer',
    'blog.posts.category.photography': 'Seyahat Fotoğrafçılığı',
    'blog.posts.category.awards': 'Ödüller & Başarılar',

    // Blog Posts
    'blog.posts.post1.title': '2024 Seyahat Trendleri ve Destinasyon Rehberi',
    'blog.posts.post1.excerpt': '2024 yılının en popüler destinasyonları ve seyahat trendleri hakkında uzman rehberlerimizin detaylı analizi ve önerileri.',
    'blog.posts.post1.author': 'Mehmet Seyhan',
    'blog.posts.post1.date': '15 Mayıs 2024',
    'blog.posts.post1.readTime': '8 dk',
    'blog.posts.post1.views': '1.2K',
    'blog.posts.post2.title': 'Kapadokya Gezi Rehberi: Balon Turu ve Gizli Güzellikler',
    'blog.posts.post2.excerpt': 'Kapadokya\'nın eşsiz güzelliklerini keşfedin. Balon turları, yeraltı şehirleri ve yerel lezzetler için kapsamlı rehber.',
    'blog.posts.post2.author': 'Ayşe Kaya',
    'blog.posts.post2.date': '12 Mayıs 2024',
    'blog.posts.post2.readTime': '6 dk',
    'blog.posts.post2.views': '890',
    'blog.posts.post3.title': 'İstanbul\'un Saklı Cenneti: Boğaziçi Kıyıları Turu',
    'blog.posts.post3.excerpt': 'Boğaziçi\'nin en güzel noktalarını keşfedin. Tarihi yapılar, yerel kafeler ve nefes kesen manzaralar.',
    'blog.posts.post3.author': 'Can Demir',
    'blog.posts.post3.date': '10 Mayıs 2024',
    'blog.posts.post3.readTime': '12 dk',
    'blog.posts.post3.views': '1.5K',
    'blog.posts.post4.title': 'Antalya\'da Lüks Otel Deneyimi: En İyi Tatil Köyleri',
    'blog.posts.post4.excerpt': 'Antalya\'nın en prestijli otellerinde unutulmaz bir tatil için rehber. Lüks konaklama ve aktivite önerileri.',
    'blog.posts.post4.author': 'Zeynep Özkan',
    'blog.posts.post4.date': '8 Mayıs 2024',
    'blog.posts.post4.readTime': '7 dk',
    'blog.posts.post4.views': '740',
    'blog.posts.post5.title': 'Türk Mutfağı Keşfi: Yerel Lezzetler Turu',
    'blog.posts.post5.excerpt': 'Türkiye\'nin farklı bölgelerindeki otantik lezzetleri keşfedin. Yerel restoranlar ve sokak yemekleri rehberi.',
    'blog.posts.post5.author': 'Ali Şahin',
    'blog.posts.post5.date': '5 Mayıs 2024',
    'blog.posts.post5.readTime': '9 dk',
    'blog.posts.post5.views': '920',
    'blog.posts.post6.title': 'Ege Sahillerinde Tekne Turu: Mavi Yolculuk Rehberi',
    'blog.posts.post6.excerpt': 'Ege\'nin berrak sularında unutulmaz bir tekne turu deneyimi. En güzel koylar ve antik şehirler.',
    'blog.posts.post6.author': 'Berat Toprak',
    'blog.posts.post6.date': '3 Mayıs 2024',
    'blog.posts.post6.readTime': '11 dk',
    'blog.posts.post6.views': '1.1K',

    // Service Detail Page
    'service-detail.features-title': 'Hizmet Özellikleri',
    'service-detail.why-choose-us': 'Neden Bizi Seçmelisiniz?',
    'service-detail.experience-title': '15+ Yıl Deneyim',
    'service-detail.experience-description': 'Turizm sektöründe kanıtlanmış başarı',
    'service-detail.expert-team-title': 'Uzman Rehber Ekibi',
    'service-detail.expert-team-description': 'Profesyonel turizm uzmanları',
    'service-detail.support-title': '7/24 Destek',
    'service-detail.support-description': 'Seyahatiniz boyunca kesintisiz hizmet',
    'service-detail.security-title': 'Güvenlik Garantisi',
    'service-detail.security-description': 'Sigortalı ve güvenli seyahat deneyimi',
    'service-detail.premium-offer-title': 'Premium Teklif Alın',
    'service-detail.premium-offer-description': 'Hizmetimiz için özel fiyat teklifi ve detaylı program bilgisi alın.',
    'service-detail.get-free-quote': 'Ücretsiz Teklif Al',
    'service-detail.other-services-title': 'Diğer Premium Hizmetlerimiz',
    'service-detail.other-services-description': 'Kapsamlı lüks turizm portföyümüzle tüm seyahat ihtiyaçlarınızı karşılıyoruz.',
    'service-detail.explore-all-services': 'Tüm Hizmetleri Keşfedin',

    // Culture Tours Service
    'service.kultur-turlari.title': 'Kültür Turları',
    'service.kultur-turlari.subtitle': 'Tarihi ve Kültürel Zenginlikleri Keşfedin',
    'service.kultur-turlari.description': 'Türkiye\'nin tarihi ve kültürel zenginliklerini keşfetmek isteyenlere özel olarak tasarlanmış rehberli kültür turları sunuyoruz.',
    'service.kultur-turlari.detailed-description': 'Kültür turlarımızda, Türkiye\'nin binlerce yıllık tarihi mirasını uzman rehberler eşliğinde keşfedeceksiniz. Antik şehirlerden Osmanlı saraylarına, müzelerden arkeolojik alanlarına kadar geniş bir yelpazede kültürel deneyimler sunuyoruz. Her turumuzu küçük gruplar halinde organize ederek, daha kişisel ve derinlemesine bir deneyim yaşatıyoruz.',
    'service.kultur-turlari.feature1': 'Uzman Rehber Eşliğinde Geziler',
    'service.kultur-turlari.feature2': 'Müze ve Antik Alan Ziyaretleri',
    'service.kultur-turlari.feature3': 'Yerel Kültür Deneyimleri',
    'service.kultur-turlari.feature4': 'Küçük Grup Turları',
    'service.kultur-turlari.feature5': 'Özel Tema Turları',
    'service.kultur-turlari.feature6': 'Fotoğraf ve Video Çekimi',
    'service.kultur-turlari.stat1.label': 'Tamamlanan Tur',
    'service.kultur-turlari.stat1.value': '250+',
    'service.kultur-turlari.stat2.label': 'Ziyaret Edilen Yer',
    'service.kultur-turlari.stat2.value': '50+',
    'service.kultur-turlari.stat3.label': 'Mutlu Müşteri',
    'service.kultur-turlari.stat3.value': '1200+',
    'service.kultur-turlari.stat4.label': 'Rehber Deneyimi',
    'service.kultur-turlari.stat4.value': '15+ Yıl',
    'service.kultur-turlari.category': 'Kültür Turları',

    // Hotel Reservation Service
    'service.otel-rezervasyonu.title': 'Otel Rezervasyonu',
    'service.otel-rezervasyonu.subtitle': 'En İyi Konaklama Seçenekleri ile Konforlu Tatil',
    'service.otel-rezervasyonu.description': 'Türkiye\'nin en güzel destinasyonlarında seçkin otellerde konaklama rezervasyonu hizmetimizle tatil planınızı kolaylaştırıyoruz.',
    'service.otel-rezervasyonu.detailed-description': 'Otel rezervasyon hizmetimizde, butik otellerden lüks resort\'lara kadar geniş bir yelpazede konaklama seçenekleri sunuyoruz. Müşterilerimizin bütçe ve tercihlerine uygun en iyi fiyat garantisi vererek, tatillerini unutulmaz kılıyoruz. Özel anlaşmalarımız sayesinde eksklüzif fırsatlar ve erken rezervasyon indirimleri sunuyoruz.',
    'service.otel-rezervasyonu.feature1': 'Boutique ve Lüks Oteller',
    'service.otel-rezervasyonu.feature2': 'En İyi Fiyat Garantisi',
    'service.otel-rezervasyonu.feature3': 'Özel Anlaşmalar ve İndirimler',
    'service.otel-rezervasyonu.feature4': 'Ücretsiz İptal Seçenekleri',
    'service.otel-rezervasyonu.feature5': '7/24 Rezervasyon Desteği',
    'service.otel-rezervasyonu.feature6': 'Özel İstekler ve Düzenlemeler',
    'service.otel-rezervasyonu.stat1.label': 'Tamamlanan Rezervasyon',
    'service.otel-rezervasyonu.stat1.value': '400+',
    'service.otel-rezervasyonu.stat2.label': 'Partner Otel',
    'service.otel-rezervasyonu.stat2.value': '75+',
    'service.otel-rezervasyonu.stat3.label': 'Müşteri Memnuniyeti',
    'service.otel-rezervasyonu.stat3.value': '%98',
    'service.otel-rezervasyonu.stat4.label': 'Ortalama İndirim',
    'service.otel-rezervasyonu.stat4.value': '%15',
    'service.otel-rezervasyonu.category': 'Otel Rezervasyonu',

    // Guide Services
    'service.rehberlik-hizmetleri.title': 'Profesyonel Rehberlik',
    'service.rehberlik-hizmetleri.subtitle': 'Deneyimli Rehberlerle Unutulmaz Geziler',
    'service.rehberlik-hizmetleri.description': 'Lisanslı ve deneyimli rehberlerimizle Türkiye\'nin her köşesini keşfedin. Kişiselleştirilmiş tur deneyimleri sunuyoruz.',
    'service.rehberlik-hizmetleri.detailed-description': 'Rehberlik hizmetlerimizde, alanında uzman ve çok dilli rehberlerimizle en kaliteli gezi deneyimini yaşatıyoruz. Her rehberimiz, bölgenin tarihini, kültürünü ve özel hikayelerini en iyi şekilde anlatabilecek deneyime sahiptir. Özel ilgi alanlarınıza göre kişiselleştirilmiş tur programları hazırlayarak, unutulmaz anılar biriktirmenizi sağlıyoruz.',
    'service.rehberlik-hizmetleri.feature1': 'Lisanslı Profesyonel Rehberler',
    'service.rehberlik-hizmetleri.feature2': 'Çoklu Dil Desteği',
    'service.rehberlik-hizmetleri.feature3': 'Kişiselleştirilmiş Tur Programları',
    'service.rehberlik-hizmetleri.feature4': 'Özel İlgi Alanları Turları',
    'service.rehberlik-hizmetleri.feature5': 'Hikaye Anlatıcılığı',
    'service.rehberlik-hizmetleri.feature6': 'Fotoğraf Çekim Yardımı',
    'service.rehberlik-hizmetleri.stat1.label': 'Rehber Sayısı',
    'service.rehberlik-hizmetleri.stat1.value': '25+',
    'service.rehberlik-hizmetleri.stat2.label': 'Dil Seçeneği',
    'service.rehberlik-hizmetleri.stat2.value': '8',
    'service.rehberlik-hizmetleri.stat3.label': 'Tur Deneyimi',
    'service.rehberlik-hizmetleri.stat3.value': '500+',
    'service.rehberlik-hizmetleri.stat4.label': 'Müşteri Puanı',
    'service.rehberlik-hizmetleri.stat4.value': '4.9/5',
    'service.rehberlik-hizmetleri.category': 'Rehberlik Hizmetleri',

    // Adventure Tours Service
    'service.macera-turlari.title': 'Macera Turları',
    'service.macera-turlari.subtitle': 'Adrenalin Dolu Deneyimler ve Doğa Sporları',
    'service.macera-turlari.description': 'Doğa severlere özel macera turları ile Türkiye\'nin eşsiz doğasında heyecan verici deneyimler yaşayın.',
    'service.macera-turlari.detailed-description': 'Macera turlarımızda, trekking\'den rafting\'e, yamaç paraşütünden kaya tırmanışına kadar geniş bir aktivite yelpazesi sunuyoruz. Güvenlik önlemlerini en üst düzeyde tutarak, adrenalin dolu ama güvenli maceralar yaşatıyoruz. Deneyimli guide\'larımız ve kaliteli ekipmanlarımızla, her seviyeden katılımcı için uygun programlar hazırlıyoruz.',
    'service.macera-turlari.feature1': 'Trekking ve Doğa Yürüyüşleri',
    'service.macera-turlari.feature2': 'Rafting ve Su Sporları',
    'service.macera-turlari.feature3': 'Yamaç Paraşütü Deneyimi',
    'service.macera-turlari.feature4': 'Kaya Tırmanışı ve Abseiling',
    'service.macera-turlari.feature5': 'Kamp ve Doğa Deneyimi',
    'service.macera-turlari.feature6': 'Güvenlik Ekipmanları Dahil',
    'service.macera-turlari.stat1.label': 'Macera Turu',
    'service.macera-turlari.stat1.value': '150+',
    'service.macera-turlari.stat2.label': 'Aktivite Çeşidi',
    'service.macera-turlari.stat2.value': '20+',
    'service.macera-turlari.stat3.label': 'Güvenlik Skoru',
    'service.macera-turlari.stat3.value': '%100',
    'service.macera-turlari.stat4.label': 'Tekrar Ziyaret',
    'service.macera-turlari.stat4.value': '%85',
    'service.macera-turlari.category': 'Macera Turları',

    // Tour Detail Page
    'tour-detail.breadcrumb.tours': 'Turlar',
    'tour-detail.tour-duration': 'Tur Süresi',
    'tour-detail.season': 'Sezon',
    'tour-detail.features-title': 'Tur Özellikleri',
    'tour-detail.info-title': 'Tur Bilgileri',
    'tour-detail.location': 'Lokasyon',
    'tour-detail.tour-organizer': 'Tur Organizatörü',
    'tour-detail.guide': 'Rehber',
    'tour-detail.partner': 'İş Ortağı',
    'tour-detail.cta.title': 'Benzer Bir Tur mu İstiyorsunuz?',
    'tour-detail.cta.description': 'Bu tura benzer bir deneyim için bizimle iletişime geçin.',
    'tour-detail.cta.button': 'İletişime Geçin',
    'tour-detail.other-tours.title': 'Diğer Turlarımız',
    'tour-detail.other-tours.description': 'Portföyümüzdeki diğer popüler turları keşfedin.',
    'tour-detail.other-tours.button': 'Tüm Turları Görüntüle',
    'tour-detail.meta.not-found': 'Tur Bulunamadı | Parla Travel',

    // Blog Detail Page
    'blog-detail.breadcrumb.blog': 'Blog',
    'blog-detail.share.title': 'Bu makaleyi paylaş',
    'blog-detail.share.button': 'Paylaş',
    'blog-detail.author.label': 'Yazar',
    'blog-detail.author.title': 'Parla Travel Uzmanı',
    'blog-detail.related.title': 'İlgili Yazılar',
    'blog-detail.related.description': 'Bu konuyla ilgili diğer yazılarımızı keşfedin.',
    'blog-detail.related.view-all': 'Tüm Blog Yazılarını Görüntüle',

    // Blog Newsletter
    'blog-detail.newsletter.title': 'Blog Güncellemelerini Kaçırmayın',
    'blog-detail.newsletter.subtitle': 'Blog Güncellemeleri',
    'blog-detail.newsletter.description': 'Seyahatteki en güncel destinasyonları, rehber önerilerini ve özel tur fırsatlarını e-posta adresinize gönderiyor,',
    'blog-detail.newsletter.description.highlight': 'keşifte öncü olmanızı sağlıyoruz',
    'blog-detail.newsletter.form.title': 'E-Bülten',
    'blog-detail.newsletter.form.subtitle': 'Haftalık güncellemeler',
    'blog-detail.newsletter.form.email.label': 'E-posta Adresiniz',
    'blog-detail.newsletter.form.email.placeholder': 'ornek@email.com',
    'blog-detail.newsletter.form.name.label': 'Adınız (İsteğe bağlı)',
    'blog-detail.newsletter.form.name.placeholder': 'Adınız Soyadınız',
    'blog-detail.newsletter.form.consent': 'KVKK kapsamında kişisel verilerimin işlenmesini ve e-posta güncellemeleri almayı kabul ediyorum.',
    'blog-detail.newsletter.form.submit': 'E-Bültene Abone Ol',
    'blog-detail.newsletter.benefits.title': 'Neler Kazanacaksınız?',
    'blog-detail.newsletter.benefits.priority.title': 'Öncelikli Bilgilendirme',
    'blog-detail.newsletter.benefits.priority.description': 'Yeni destinasyon rehberleri ve özel tur fırsatlarından ilk siz haberdar olun.',
    'blog-detail.newsletter.benefits.analysis.title': 'Destinasyon Analizleri',
    'blog-detail.newsletter.benefits.analysis.description': 'Detaylı destinasyon rehberleri ve seyahat önerileri.',
    'blog-detail.newsletter.benefits.offers.title': 'Özel Tur Fırsatları',
    'blog-detail.newsletter.benefits.offers.description': 'Sadece abone olanlara özel tur indirimleri ve erken rezervasyon fırsatları.',
    'blog-detail.newsletter.stats.subscribers': 'Aktif Abone',
    'blog-detail.newsletter.stats.satisfaction': 'Memnuniyet Oranı',

    // Blog Detail Metadata
    'blog-detail.meta.not-found': 'Blog Yazısı Bulunamadı | Parla Travel',
    'blog-detail.meta.blog-suffix': '| Parla Travel Blog',
    
    // Service Detail Metadata
    'service-detail.meta.not-found': 'Hizmet Bulunamadı | Parla Travel',
    'service-detail.meta.description': 'Türkiye\'nin en güzel destinasyonlarında unutulmaz seyahat deneyimleri yaşayın.',
    'service-detail.meta.culture-tours': 'Kültür Turları',
    'service-detail.meta.hotel-reservation': 'Otel Rezervasyonu',
    'service-detail.meta.guide-services': 'Profesyonel Rehberlik',
    'service-detail.meta.adventure-tours': 'Macera Turları',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.tours': 'Tours',
    'nav.about': 'About',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    
    // Services
    'services.culture-tours': 'Cultural Tours',
    'services.hotel-reservations': 'Hotel Reservations',
    'services.guide-services': 'Guide Services',
    'services.adventure-tours': 'Adventure Tours',
    
    // Hero Section - Slides
    'hero.slide1.title': 'Unique Turkey Tours',
    'hero.slide1.description': 'Discover Turkey\'s rich cultural heritage and create unforgettable memories.',
    'hero.slide2.title': 'Luxury Hotel Reservations',
    'hero.slide2.description': 'We make your vacation experience perfect with comfortable accommodation options.',
    'hero.slide3.title': 'Cultural Tours and Guidance',
    'hero.slide3.description': 'Discover historical and cultural riches with our expert guides.',
    'hero.slide4.title': 'Special Holiday Packages',
    'hero.slide4.description': 'Live your dream travel with our specially prepared holiday packages.',
    'hero.cta.tours': 'Our Tours',
    'hero.cta.hotels': 'Hotels',
    'hero.cta.culture': 'Cultural Tours',
    'hero.cta.packages': 'Packages',
    'hero.cta.services': 'Our Services',
    'hero.video.title': 'Discovery Video',
    'hero.scroll.text': 'Scroll',
    
    // Hero highlights for text styling
    'hero.highlight.memories': 'unforgettable memories',
    'hero.highlight.perfect': 'perfect with',
    'hero.highlight.discover': 'cultural riches',
    'hero.highlight.travel': 'dream travel',
    'hero.video.coming-soon': 'Promotional video coming soon...',
    
    // Services Section
    'services.title': 'Our Service',
    'services.title.highlight': 'Areas',
    'services.description': 'With our 15 years of experience, we provide comprehensive services in tourism, travel and guidance.',
    'services.view-details': 'View Details',
    'services.cta.title': 'Get a Quote for Your Dream Tour',
    'services.cta.description': 'Evaluate your travel plan with our expert team and discover tours tailored just for you.',
    'services.cta.button': 'Free Consultation',
    
    // Tours Section
    'tours.title': 'Featured',
    'tours.title.highlight': 'Tours',
    'tours.description': 'Discover our most popular destinations and create unforgettable memories.',
    'tours.view-all': 'View All Tours',
    'tours.duration': 'days',
    'tours.from': 'from',
    
    // About Section
    'about.title': 'About Us',
    'about.description': 'We are a leading company in the tourism sector with 15 years of experience, introducing the beauties of Turkey to the world.',
    
    // Contact Section
    'contact.title': 'Contact',
    'contact.get-in-touch': 'Get in Touch',
    'contact.description': 'Contact us for your questions, we are here to provide you with the best service.',
    
    // Contact Hero Section
    'contact.hero.title.main': 'Get in',
    'contact.hero.title.highlight': 'Touch',
    'contact.hero.description': 'Contact us for information about your travel plans, making reservations or special tour requests',
    'contact.hero.description.highlight': ' get in touch with us',
    'contact.hero.stats.service.value': '24/7',
    'contact.hero.stats.service.label': 'Reservation Services',
    'contact.hero.stats.response.value': '<1',
    'contact.hero.stats.response.label': 'Hour Response Time',
    
    // Contact Info Cards
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.number': '+90 212 555 0123',
    'contact.info.phone.hours': 'Monday - Friday: 09:00 - 18:00',
    'contact.info.email.title': 'Email',
    'contact.info.email.address': 'info@parlatravel.com',
    'contact.info.email.support': '24/7 email support',
    'contact.info.address.title': 'Address',
    'contact.info.address.street': 'Maslak Mahallesi, Büyükdere Cad.',
    'contact.info.address.details': 'No:123 Sarıyer/Istanbul',
    'footer.address.street': 'Taksim Square, Istiklal Street',
    'footer.address.details': 'No: 250, Beyoğlu/Istanbul',
    'contact.info.hours.title': 'Office Hours',
    'contact.info.hours.weekdays': 'Monday - Friday: 09:00 - 18:00',
    'contact.info.hours.saturday': 'Saturday: 09:00 - 14:00',
    
    // Contact Form Section
    'contact.form.title': 'Create Your Travel Request',
    'contact.form.description': 'Fill out the form below for an unforgettable travel experience.',
    'contact.form.description.support': 'Our expert team will contact you within 24 hours to prepare your personalized travel plan.',
    
    // Form Fields
    'contact.form.name.label': 'Full Name',
    'contact.form.name.placeholder': 'Your Full Name',
    'contact.form.email.label': 'Email',
    'contact.form.email.placeholder': 'example@email.com',
    'contact.form.phone.label': 'Phone',
    'contact.form.phone.placeholder': '+90 5XX XXX XX XX',
    'contact.form.company.label': 'Company/Organization',
    'contact.form.company.placeholder': 'Company Name',
    'contact.form.service.label': 'Service Type',
    'contact.form.service.placeholder': 'Select service',
    'contact.form.service.cultural-tours': 'Cultural Tours',
    'contact.form.service.custom-tours': 'Custom Tour Organization',
    'contact.form.service.hotel-reservation': 'Hotel Reservation',
    'contact.form.service.group-tours': 'Group Tours',
    'contact.form.service.guide-services': 'Professional Guide Services',
    'contact.form.service.other': 'Other',
    'contact.form.budget.label': 'Budget Range',
    'contact.form.budget.placeholder': 'Select budget',
    'contact.form.budget.5k-15k': '5,000 - 15,000 TL',
    'contact.form.budget.15k-30k': '15,000 - 30,000 TL',
    'contact.form.budget.30k-50k': '30,000 - 50,000 TL',
    'contact.form.budget.50k+': '50,000 TL+',
    'contact.form.timeline.label': 'Travel Time',
    'contact.form.timeline.placeholder': 'Select time',
    'contact.form.timeline.asap': 'As soon as possible',
    'contact.form.timeline.1-month': 'Within 1 month',
    'contact.form.timeline.3-months': 'Within 3 months',
    'contact.form.timeline.6-months': 'Within 6 months',
    'contact.form.timeline.flexible': 'Flexible',
    'contact.form.message.label': 'Travel Details',
    'contact.form.message.placeholder': 'Describe the details of your travel plan, places you want to visit, special requests and expectations...',
    'contact.form.consent.text': 'I accept the processing of my personal data within the scope of GDPR and being contacted.',
    'contact.form.submit.text': 'Send Travel Request',
    
    // Form Process Info
    'contact.form.process.title': 'After Submitting the Form',
    'contact.form.process.step1.title': 'Confirmation Email',
    'contact.form.process.step1.description': 'Request received message comes to your email instantly',
    'contact.form.process.step2.title': 'Initial Contact',
    'contact.form.process.step2.description': 'Our expert team will contact you within 24 hours',
    'contact.form.process.step3.title': 'Detailed Offer',
    'contact.form.process.step3.description': 'We present our comprehensive offer within 3-5 days',
    
    // Quick Contact
    'contact.form.quick.title': 'Quick Contact',
    'contact.form.quick.description': 'If you prefer to call directly for urgent matters:',
    'contact.form.quick.phone': '+90 212 555 0123',
    'contact.form.quick.email': 'info@parlatravel.com',
    
    // Contact Page Metadata
    'contact.meta.title': 'Contact | Parla Travel',
    'contact.meta.description': 'Contact Parla Travel. Get a quote for your tour reservation and discuss with our expert team.',
    
    // Footer
    'footer.company.description': 'With 15+ years of experience in tourism and travel, we organize unforgettable tours for you to discover Turkey\'s most beautiful destinations.',
    'footer.services.title': 'Our Services',
    'footer.services.culture-tours': 'Cultural Tours',
    'footer.services.hotel-reservations': 'Hotel Reservations',
    'footer.services.guide-services': 'Guide Services',
    'footer.services.adventure-tours': 'Adventure Tours',
    'footer.quick-links.title': 'Quick Links',
    'footer.quick-links.about': 'About',
    'footer.quick-links.tours': 'Tours',
    'footer.quick-links.blog': 'Blog',
    'footer.quick-links.career': 'Career',
    'footer.quick-links.contact': 'Contact',
    'footer.social.facebook': 'Facebook',
    'footer.social.instagram': 'Instagram',
    'footer.social.linkedin': 'LinkedIn',
    'footer.social.twitter': 'Twitter',
    'footer.copyright': 'Parla Travel. All rights reserved.',
    'footer.privacy-policy': 'Privacy Policy',
    'footer.terms-of-service': 'Terms of Service',
    'footer.developed-by': 'Designed & Developed by',
    'footer.description': 'We provide professional tourism services for you to discover the most beautiful places in Turkey.',
    'footer.quick-links': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.contact-info': 'Contact Information',
    'footer.rights': 'All rights reserved.',
    
    // Company Stats
    'stats.years': 'Years Experience',
    'stats.tours': 'Tours Completed',
    'stats.customers': 'Happy Customers',
    'stats.destinations': 'Destinations',
    
    // Service Details
    'services.culture-tours.description': 'Discover Turkey\'s rich historical and cultural heritage, experience unforgettable experiences with our expert guides.',
    'services.culture-tours.features': 'Historical Places, Museum Tours, Ancient Cities, Local Culture',
    'services.culture-tours.process': '1-15 Days',
    'services.hotel-reservations.description': 'We offer reservation services in the best hotels for a comfortable accommodation experience, options suitable for every budget.',
    'services.hotel-reservations.features': 'Luxury Hotels, Boutique Hotels, Boutique Pensions, Private Villas',
    'services.hotel-reservations.process': '1-7 Days',
    'services.guide-services.description': 'Discover every corner of Turkey with our professional and experienced guides, personal and group tours.',
    'services.guide-services.features': 'Personal Guidance, Group Guidance, Multilingual Service, Special Interest Areas',
    'services.guide-services.process': '1-30 Days',
    'services.adventure-tours.description': 'Live your dream travel with our specially prepared holiday packages for you, completely customizable.',
    'services.adventure-tours.features': 'VIP Tours, Romantic Tours, Adventure Tours, Gastronomy Tours',
    'services.adventure-tours.process': '3-21 Days',

    // Featured Tours Section
    'featured-tours.title': 'Featured',
    'featured-tours.title.highlight': 'Tours',
    'featured-tours.description': 'Experience unforgettable moments in our most popular destinations. Discover the most beautiful places of Turkey with our expert guides.',
    'featured-tours.filter.all': 'All',
    'featured-tours.filter.cultural': 'Cultural',
    'featured-tours.filter.natural': 'Natural',
    'featured-tours.filter.adventure': 'Adventure',
    'featured-tours.category.cultural': 'Cultural',
    'featured-tours.category.natural': 'Natural',
    'featured-tours.category.adventure': 'Adventure',
    'featured-tours.category.general': 'General',
    'featured-tours.view-details': 'View Details',
    'featured-tours.explore': 'Explore',
    'featured-tours.tour-duration': 'Tour Duration',
    'featured-tours.cta.description': 'Check out our complete list for more tour options.',
    'featured-tours.view-all': 'View All Tours',

    // Services Preview Section
    'services-preview.badge': 'Our Expert Services',
    'services-preview.title.main': 'Exploring',
    'services-preview.title.highlight': 'Turkey',
    'services-preview.description': 'With our 15+ years of experience in tourism and travel',
    'services-preview.description.highlight': ' unforgettable experiences',
    'services-preview.description.end': ' we provide.',
    'services-preview.stats.tours': 'Tours Completed',
    'services-preview.stats.experience': 'Years Experience',
    'services-preview.stats.visitors': 'Happy Visitors',
    
    // Service Cards
    'services-preview.service.culture-tours.title': 'Cultural Tours',
    'services-preview.service.culture-tours.short': 'History and culture discovery',
    'services-preview.service.culture-tours.description': 'Discover Turkey\'s rich historical and cultural heritage. Experience unforgettable moments with our expert guides.',
    'services-preview.service.culture-tours.feature1': 'Historical Places',
    'services-preview.service.culture-tours.feature2': 'Museum Tours',
    'services-preview.service.culture-tours.feature3': 'Local Culture',
    
    'services-preview.service.hotel-reservations.title': 'Hotel Reservations',
    'services-preview.service.hotel-reservations.short': 'Quality accommodation solutions',
    'services-preview.service.hotel-reservations.description': 'We offer reservation services at the best hotels for a comfortable accommodation experience. Options available for every budget.',
    'services-preview.service.hotel-reservations.feature1': 'Luxury Hotels',
    'services-preview.service.hotel-reservations.feature2': 'Boutique Hotels',
    'services-preview.service.hotel-reservations.feature3': 'Budget Options',
    
    'services-preview.service.guide-services.title': 'Guide Services',
    'services-preview.service.guide-services.short': 'Expert guidance support',
    'services-preview.service.guide-services.description': 'Discover every corner of Turkey with our professional and experienced guides. Special service for personal and group tours.',
    'services-preview.service.guide-services.feature1': 'Personal Guidance',
    'services-preview.service.guide-services.feature2': 'Group Tours',
    'services-preview.service.guide-services.feature3': 'Language Support',
    
    'services-preview.tour-label': 'Tours',
    'services-preview.premium-label': 'Premium',
    'services-preview.guarantee-label': 'Guarantee',
    'services-preview.button.explore': 'Explore Details',

    // Services Hero
    'services-hero.professional': 'Professional',
    'services-hero.services': 'Services',
    'services-hero.description': 'From cultural tours to hotel reservations, from guide services to special tours, we offer services in a wide range,',
    'services-hero.description.highlight': 'we provide unforgettable experiences',
    'services-hero.stats.tours': 'Tours Organized',
    'services-hero.stats.visitors': 'Happy Visitors',
    'services-hero.established': 'EST. 2008',

    // Service Process
    'service-process.title': 'Our Working',
    'service-process.title.highlight': 'Process',
    'service-process.description': 'We adopt a systematic approach to each tour and follow a four-stage process for unforgettable experiences.',
    'service-process.step1.title': 'Consultation & Planning',
    'service-process.step1.description': 'We analyze your travel needs in detail and make personalized plans.',
    'service-process.step1.duration': '1-3 Days',
    'service-process.step1.details': 'Analysis of your travel preferences, Budget planning and suggestion packages, Date and duration planning, Evaluation of your special requests',
    'service-process.step2.title': 'Program & Route Design',
    'service-process.step2.description': 'We develop tour programs special to you with our expert team, design unique experiences.',
    'service-process.step2.duration': '2-5 Days',
    'service-process.step2.details': 'Special route and program preparation, Destination selection and activity plan, Revision and optimization process, Final program approval and detailing',
    'service-process.step3.title': 'Reservation & Organization',
    'service-process.step3.description': 'We organize all the details of your tour with professional reservation services, providing hassle-free travels.',
    'service-process.step3.duration': '3-7 Days',
    'service-process.step3.details': 'Hotel and accommodation reservations, Transportation and transfer organization, Activity and tour reservations, Insurance and legal process tracking',
    'service-process.step4.title': 'Guidance & Service',
    'service-process.step4.description': 'We realize your tour with professional guidance service and offer perfect experiences.',
    'service-process.step4.duration': '1-30 Days',
    'service-process.step4.details': 'Tour execution with expert guide, 24/7 support and help line, Resolution of instant problems, Post-tour satisfaction follow-up',
    'service-process.in-this-step': 'In This Step:',
    'service-process.step': 'Step',
    'service-process.preparation': 'Tour Preparation Process',
    'service-process.estimated-time': 'Estimated Time',
    'service-process.previous-step': 'Previous Step',
    'service-process.next-step': 'Next Step',

    // Services CTA
    'services-cta.title': 'Let\'s Plan Your',
    'services-cta.title.highlight': 'Journey Together',
    'services-cta.description': 'With our 15 years of experience and expert team, we organize your trip in the best way.',
    'services-cta.description.highlight': 'We provide unforgettable experiences',
    'services-cta.contact.phone': 'Phone',
    'services-cta.contact.phone.number': '+90 212 555 0156',
    'services-cta.contact.email': 'Email',
    'services-cta.contact.email.address': 'info@parlagroup.com',
    'services-cta.contact.address': 'Address',
    'services-cta.contact.address.location': 'Taksim, Istanbul',
    'services-cta.cta.get-prices': 'Get Tour Prices',
    'services-cta.cta.call-now': 'Call Now',
    'services-cta.testimonials.title': 'Customer',
    'services-cta.testimonials.title.highlight': 'Reviews',
    'services-cta.testimonial1.name': 'Mehmet Demir',
    'services-cta.testimonial1.company': 'Ankara',
    'services-cta.testimonial1.comment': 'We joined our Cappadocia tour with Parla Travel. We had an unforgettable experience with professional guide services and excellent organization.',
    'services-cta.testimonial2.name': 'Ayşe Çelik',
    'services-cta.testimonial2.company': 'Izmir',
    'services-cta.testimonial2.comment': 'The care and knowledge they showed in our Istanbul cultural tour is truly commendable. Every detail was thought out, it was a wonderful trip.',
    'services-cta.stats.tours': 'Tours Organized',
    'services-cta.stats.visitors': 'Happy Visitors',
    'services-cta.support.title': '24/7 Customer Support',
    'services-cta.support.description': 'We are ready to support you in every aspect of your travel.',

    // Common
    'common.read-more': 'Read More',
    'common.learn-more': 'Learn More',
    'common.book-now': 'Book Now',
    'common.get-quote': 'Get Quote',
    'common.view-details': 'View Details',

    // Tours Page
    // Tours Hero Section
    'tours-page.hero.breadcrumb.home': 'Home',
    'tours-page.hero.breadcrumb.tours': 'Our Tours',
    'tours-page.hero.title.popular': 'Popular',
    'tours-page.hero.title.tours': 'Tours',
    'tours-page.hero.description.main': 'With our 650+ successful tour experiences, we offer a wide portfolio from cultural tours to nature tours,',
    'tours-page.hero.description.highlight': 'creating unforgettable memories',
    'tours-page.hero.category.cultural-tours': 'Cultural Tours',
    'tours-page.hero.category.cultural-tours.count': '220+ Tours',
    'tours-page.hero.category.guide-services': 'Guide Services',
    'tours-page.hero.category.guide-services.count': '150+ Tours',
    'tours-page.hero.category.special-tours': 'Special Tours',
    'tours-page.hero.category.special-tours.count': '100+ Tours',
    'tours-page.hero.established': 'EST. 2008',

    // Tours Filter Section
    'tours-page.filter.all': 'All',
    'tours-page.filter.cultural': 'Cultural Tours',
    'tours-page.filter.nature': 'Nature Tours',
    'tours-page.filter.adventure': 'Adventure Tours',
    'tours-page.filter.city': 'City Tours',

    // Tours Grid Section
    'tours-page.grid.category.all': 'All Tours',
    'tours-page.grid.category.cultural': 'Cultural Tours',
    'tours-page.grid.category.nature': 'Nature Tours',
    'tours-page.grid.category.adventure': 'Adventure Tours',
    'tours-page.grid.category.city': 'City Tours',
    'tours-page.grid.category.tours': 'Tours',
    'tours-page.grid.tours-found': 'tours found',
    'tours-page.grid.view-tour': 'View Tour',
    'tours-page.grid.tour-details': 'Tour Details',
    'tours-page.grid.load-more': 'More Tours',

    // Tours Data
    'tours-page.tour.istanbul-culture.title': 'Istanbul Culture Tour',
    'tours-page.tour.istanbul-culture.category': 'Cultural Tours',
    'tours-page.tour.istanbul-culture.location': 'Istanbul, Turkey',
    'tours-page.tour.istanbul-culture.description': 'We discover all the beauties of Istanbul from historic Sultanahmet to modern Beyoğlu.',
    'tours-page.tour.cappadocia-balloon.title': 'Cappadocia Balloon Tour',
    'tours-page.tour.cappadocia-balloon.category': 'Adventure Tours',
    'tours-page.tour.cappadocia-balloon.location': 'Cappadocia, Nevşehir',
    'tours-page.tour.cappadocia-balloon.description': 'The unforgettable experience of discovering Cappadocia\'s unique landscape with hot air balloon tour.',
    'tours-page.tour.pamukkale-nature.title': 'Pamukkale Nature Tour',
    'tours-page.tour.pamukkale-nature.category': 'Nature Tours',
    'tours-page.tour.pamukkale-nature.location': 'Pamukkale, Denizli',
    'tours-page.tour.pamukkale-nature.description': 'Discovery of natural wonder Pamukkale with white travertines and ancient Hierapolis ruins.',
    'tours-page.tour.antalya-city.title': 'Antalya City Tour',
    'tours-page.tour.antalya-city.category': 'City Tours',
    'tours-page.tour.antalya-city.location': 'Antalya, Turkey',
    'tours-page.tour.antalya-city.description': 'Experience Antalya\'s unique beauties with the turquoise waters of the Mediterranean and historic Kaleiçi.',
    'tours-page.tour.ephesus-ancient.title': 'Ephesus Ancient City Tour',
    'tours-page.tour.ephesus-ancient.category': 'Cultural Tours',
    'tours-page.tour.ephesus-ancient.location': 'Ephesus, İzmir',
    'tours-page.tour.ephesus-ancient.description': 'Journey in the historical atmosphere of Ephesus, one of the best preserved cities of the ancient world.',
    'tours-page.tour.blacksea-highlands.title': 'Black Sea Highlands Tour',
    'tours-page.tour.blacksea-highlands.category': 'Nature Tours',
    'tours-page.tour.blacksea-highlands.location': 'Black Sea Region',
    'tours-page.tour.blacksea-highlands.description': 'A peaceful escape experience with the lush green highlands and natural beauties of the Black Sea.',

    // Tours CTA Section
    'tours-page.cta.title.main': 'Let\'s Plan Your',
    'tours-page.cta.title.highlight': 'Dream Journey Together',
    'tours-page.cta.description.main': 'With our 650+ successful tour experiences, we can make your dream journey come true too.',
    'tours-page.cta.description.highlight': 'We create unforgettable memories',
    'tours-page.cta.button.plan-trip': 'Plan Your Trip',
    'tours-page.cta.button.download-catalog': 'Download Tour Catalog',
    'tours-page.cta.button.share': 'Share',
    'tours-page.cta.stats.tours.number': '650+',
    'tours-page.cta.stats.tours.label': 'Tours Organized',
    'tours-page.cta.stats.experience.number': '15+',
    'tours-page.cta.stats.experience.label': 'Years Experience',
    'tours-page.cta.stats.visitors.number': '12000+',
    'tours-page.cta.stats.visitors.label': 'Happy Visitors',
    'tours-page.cta.stats.destinations.number': '45+',
    'tours-page.cta.stats.destinations.label': 'Destinations',

    // Tours Page Metadata
    'tours-page.meta.title': 'Turkey Tours - Popular Destinations | Parla Travel',
    'tours-page.meta.description': 'Discover Turkey\'s most beautiful destinations in our wide portfolio from cultural tours to nature trips, from adventure tours to city tours.',

    // Blog Page
    // Blog Hero Section
    'blog.hero.title.main': 'Blog &',
    'blog.hero.title.highlight': 'News',
    'blog.hero.description.main': 'Follow the latest developments in the world of travel, tourism and discovery.',
    'blog.hero.description.highlight': 'Discover our expert guide recommendations',
    'blog.hero.stats.posts.value': '150+',
    'blog.hero.stats.posts.label': 'Blog Posts',
    'blog.hero.stats.readers.value': '25K+',
    'blog.hero.stats.readers.label': 'Readers',
    'blog.hero.stats.categories.value': '15+',
    'blog.hero.stats.categories.label': 'Categories',
    'blog.hero.featured.alt': '2024 Travel Trends and Destination Guide',
    'blog.hero.featured.badge': 'Featured',
    'blog.hero.featured.title': '2024 Travel Trends and Destination Guide',
    'blog.hero.featured.description': 'Detailed analysis and recommendations from our expert guides on the most popular destinations and travel trends of 2024.',
    'blog.hero.featured.date': 'May 15, 2024',
    'blog.hero.featured.author': 'Mehmet Seyhan',
    'blog.hero.featured.views': '1.2K',
    'blog.hero.featured.read-more': 'Read More',

    // Blog Categories
    'blog.categories.title': 'Blog Categories',
    'blog.categories.description': 'Discover content according to your interests and follow developments in the sector.',
    'blog.categories.all.name': 'All',
    'blog.categories.all.description': 'All blog posts',
    'blog.categories.destinations.name': 'Destinations',
    'blog.categories.destinations.description': 'Popular travel destinations and guides',
    'blog.categories.travel-guides.name': 'Travel Guides',
    'blog.categories.travel-guides.description': 'Detailed travel plans and recommendations',
    'blog.categories.accommodation.name': 'Accommodation',
    'blog.categories.accommodation.description': 'Hotel recommendations and accommodation guides',
    'blog.categories.gastronomy.name': 'Gastronomy',
    'blog.categories.gastronomy.description': 'Local flavors and culinary experiences',
    'blog.categories.team.name': 'Team & Career',
    'blog.categories.team.description': 'Team stories and tourism careers',
    'blog.categories.photography.name': 'Travel Photography',
    'blog.categories.photography.description': 'Photography tips and most beautiful shots',
    'blog.categories.awards.name': 'Awards & Achievements',
    'blog.categories.awards.description': 'Awards we received and success stories',
    'blog.categories.selected': 'Selected category',
    'blog.categories.posts': 'posts',

    // Blog Grid
    'blog.grid.title.all': 'Latest Blog Posts',
    'blog.grid.title.filtered': 'Filtered Posts',
    'blog.grid.no-posts': 'No posts found in this category yet.',
    'blog.grid.posts-found': 'posts found',
    'blog.grid.featured': 'Featured',
    'blog.grid.read-more': 'Read More',
    'blog.grid.load-more': 'Load More',

    // Blog Post Categories
    'blog.posts.category.travel-guide': 'Travel Guide',
    'blog.posts.category.destination': 'Destination',
    'blog.posts.category.city-tours': 'City Tours',
    'blog.posts.category.accommodation': 'Accommodation',
    'blog.posts.category.gastronomy': 'Gastronomy',
    'blog.posts.category.blue-tour': 'Blue Tour',
    'blog.posts.category.team': 'Team & Career',
    'blog.posts.category.photography': 'Travel Photography',
    'blog.posts.category.awards': 'Awards & Achievements',

    // Blog Posts
    'blog.posts.post1.title': '2024 Travel Trends and Destination Guide',
    'blog.posts.post1.excerpt': 'Detailed analysis and recommendations from our expert guides on the most popular destinations and travel trends of 2024.',
    'blog.posts.post1.author': 'Mehmet Seyhan',
    'blog.posts.post1.date': 'May 15, 2024',
    'blog.posts.post1.readTime': '8 min',
    'blog.posts.post1.views': '1.2K',
    'blog.posts.post2.title': 'Cappadocia Travel Guide: Balloon Tour and Hidden Beauties',
    'blog.posts.post2.excerpt': 'Discover the unique beauties of Cappadocia. Comprehensive guide for balloon tours, underground cities and local flavors.',
    'blog.posts.post2.author': 'Ayşe Kaya',
    'blog.posts.post2.date': 'May 12, 2024',
    'blog.posts.post2.readTime': '6 min',
    'blog.posts.post2.views': '890',
    'blog.posts.post3.title': 'Istanbul\'s Hidden Paradise: Bosphorus Shores Tour',
    'blog.posts.post3.excerpt': 'Discover the most beautiful spots of the Bosphorus. Historical buildings, local cafes and breathtaking views.',
    'blog.posts.post3.author': 'Can Demir',
    'blog.posts.post3.date': 'May 10, 2024',
    'blog.posts.post3.readTime': '12 min',
    'blog.posts.post3.views': '1.5K',
    'blog.posts.post4.title': 'Luxury Hotel Experience in Antalya: Best Resorts',
    'blog.posts.post4.excerpt': 'Guide for an unforgettable vacation at Antalya\'s most prestigious hotels. Luxury accommodation and activity recommendations.',
    'blog.posts.post4.author': 'Zeynep Özkan',
    'blog.posts.post4.date': 'May 8, 2024',
    'blog.posts.post4.readTime': '7 min',
    'blog.posts.post4.views': '740',
    'blog.posts.post5.title': 'Turkish Cuisine Discovery: Local Flavors Tour',
    'blog.posts.post5.excerpt': 'Discover authentic flavors from different regions of Turkey. Local restaurants and street food guide.',
    'blog.posts.post5.author': 'Ali Şahin',
    'blog.posts.post5.date': 'May 5, 2024',
    'blog.posts.post5.readTime': '9 min',
    'blog.posts.post5.views': '920',
    'blog.posts.post6.title': 'Boat Tour on Aegean Shores: Blue Voyage Guide',
    'blog.posts.post6.excerpt': 'Unforgettable boat tour experience in the crystal clear waters of the Aegean. Most beautiful bays and ancient cities.',
    'blog.posts.post6.author': 'Berat Toprak',
    'blog.posts.post6.date': 'May 3, 2024',
    'blog.posts.post6.readTime': '11 min',
    'blog.posts.post6.views': '1.1K',

    // Service Detail Page
    'service-detail.features-title': 'Service Features',
    'service-detail.why-choose-us': 'Why Choose Us?',
    'service-detail.experience-title': '15+ Years Experience',
    'service-detail.experience-description': 'Proven success in tourism industry',
    'service-detail.expert-team-title': 'Expert Guide Team',
    'service-detail.expert-team-description': 'Professional tourism experts',
    'service-detail.support-title': '24/7 Support',
    'service-detail.support-description': 'Continuous service throughout your journey',
    'service-detail.security-title': 'Security Guarantee',
    'service-detail.security-description': 'Insured and safe travel experience',
    'service-detail.premium-offer-title': 'Get Premium Quote',
    'service-detail.premium-offer-description': 'Get special price quotes and detailed program information for our service.',
    'service-detail.get-free-quote': 'Get Free Quote',
    'service-detail.other-services-title': 'Our Other Premium Services',
    'service-detail.other-services-description': 'We meet all your travel needs with our comprehensive luxury tourism portfolio.',
    'service-detail.explore-all-services': 'Explore All Services',

    // Culture Tours Service
    'service.kultur-turlari.title': 'Cultural Tours',
    'service.kultur-turlari.subtitle': 'Discover Historical and Cultural Treasures',
    'service.kultur-turlari.description': 'We offer guided cultural tours specially designed for those who want to explore Turkey\'s historical and cultural riches.',
    'service.kultur-turlari.detailed-description': 'In our cultural tours, you will discover Turkey\'s thousands of years of historical heritage with expert guides. We offer cultural experiences in a wide range from ancient cities to Ottoman palaces, from museums to archaeological sites. We organize each tour in small groups to provide a more personal and in-depth experience.',
    'service.kultur-turlari.feature1': 'Expert Guided Tours',
    'service.kultur-turlari.feature2': 'Museum and Ancient Site Visits',
    'service.kultur-turlari.feature3': 'Local Cultural Experiences',
    'service.kultur-turlari.feature4': 'Small Group Tours',
    'service.kultur-turlari.feature5': 'Special Themed Tours',
    'service.kultur-turlari.feature6': 'Photography and Video Shooting',
    'service.kultur-turlari.stat1.label': 'Tours Completed',
    'service.kultur-turlari.stat1.value': '250+',
    'service.kultur-turlari.stat2.label': 'Places Visited',
    'service.kultur-turlari.stat2.value': '50+',
    'service.kultur-turlari.stat3.label': 'Happy Customers',
    'service.kultur-turlari.stat3.value': '1200+',
    'service.kultur-turlari.stat4.label': 'Guide Experience',
    'service.kultur-turlari.stat4.value': '15+ Years',
    'service.kultur-turlari.category': 'Cultural Tours',

    // Hotel Reservation Service
    'service.otel-rezervasyonu.title': 'Hotel Reservations',
    'service.otel-rezervasyonu.subtitle': 'Comfortable Vacation with Best Accommodation Options',
    'service.otel-rezervasyonu.description': 'We make your vacation plans easier with our accommodation reservation service at distinguished hotels in Turkey\'s most beautiful destinations.',
    'service.otel-rezervasyonu.detailed-description': 'In our hotel reservation service, we offer accommodation options ranging from boutique hotels to luxury resorts. We make their vacations unforgettable by providing the best price guarantee suitable for our customers\' budgets and preferences. We offer exclusive opportunities and early booking discounts through our special agreements.',
    'service.otel-rezervasyonu.feature1': 'Boutique and Luxury Hotels',
    'service.otel-rezervasyonu.feature2': 'Best Price Guarantee',
    'service.otel-rezervasyonu.feature3': 'Special Deals and Discounts',
    'service.otel-rezervasyonu.feature4': 'Free Cancellation Options',
    'service.otel-rezervasyonu.feature5': '24/7 Reservation Support',
    'service.otel-rezervasyonu.feature6': 'Special Requests and Arrangements',
    'service.otel-rezervasyonu.stat1.label': 'Reservations Completed',
    'service.otel-rezervasyonu.stat1.value': '400+',
    'service.otel-rezervasyonu.stat2.label': 'Partner Hotels',
    'service.otel-rezervasyonu.stat2.value': '75+',
    'service.otel-rezervasyonu.stat3.label': 'Customer Satisfaction',
    'service.otel-rezervasyonu.stat3.value': '98%',
    'service.otel-rezervasyonu.stat4.label': 'Average Discount',
    'service.otel-rezervasyonu.stat4.value': '15%',
    'service.otel-rezervasyonu.category': 'Hotel Reservations',

    // Guide Services
    'service.rehberlik-hizmetleri.title': 'Professional Guidance',
    'service.rehberlik-hizmetleri.subtitle': 'Unforgettable Tours with Experienced Guides',
    'service.rehberlik-hizmetleri.description': 'Discover every corner of Turkey with our licensed and experienced guides. We offer personalized tour experiences.',
    'service.rehberlik-hizmetleri.detailed-description': 'In our guidance services, we provide the highest quality travel experience with our expert and multilingual guides. Each of our guides has the experience to best tell the history, culture and special stories of the region. We help you collect unforgettable memories by preparing personalized tour programs according to your special interests.',
    'service.rehberlik-hizmetleri.feature1': 'Licensed Professional Guides',
    'service.rehberlik-hizmetleri.feature2': 'Multilingual Support',
    'service.rehberlik-hizmetleri.feature3': 'Personalized Tour Programs',
    'service.rehberlik-hizmetleri.feature4': 'Special Interest Tours',
    'service.rehberlik-hizmetleri.feature5': 'Storytelling',
    'service.rehberlik-hizmetleri.feature6': 'Photography Assistance',
    'service.rehberlik-hizmetleri.stat1.label': 'Number of Guides',
    'service.rehberlik-hizmetleri.stat1.value': '25+',
    'service.rehberlik-hizmetleri.stat2.label': 'Language Options',
    'service.rehberlik-hizmetleri.stat2.value': '8',
    'service.rehberlik-hizmetleri.stat3.label': 'Tour Experience',
    'service.rehberlik-hizmetleri.stat3.value': '500+',
    'service.rehberlik-hizmetleri.stat4.label': 'Customer Rating',
    'service.rehberlik-hizmetleri.stat4.value': '4.9/5',
    'service.rehberlik-hizmetleri.category': 'Guide Services',

    // Adventure Tours Service
    'service.macera-turlari.title': 'Adventure Tours',
    'service.macera-turlari.subtitle': 'Adrenaline-Filled Experiences and Nature Sports',
    'service.macera-turlari.description': 'Experience exciting adventures in Turkey\'s unique nature with adventure tours specially designed for nature lovers.',
    'service.macera-turlari.detailed-description': 'In our adventure tours, we offer a wide range of activities from trekking to rafting, from paragliding to rock climbing. By keeping safety measures at the highest level, we provide adrenaline-filled but safe adventures. With our experienced guides and quality equipment, we prepare suitable programs for participants of all levels.',
    'service.macera-turlari.feature1': 'Trekking and Nature Walks',
    'service.macera-turlari.feature2': 'Rafting and Water Sports',
    'service.macera-turlari.feature3': 'Paragliding Experience',
    'service.macera-turlari.feature4': 'Rock Climbing and Abseiling',
    'service.macera-turlari.feature5': 'Camping and Nature Experience',
    'service.macera-turlari.feature6': 'Safety Equipment Included',
    'service.macera-turlari.stat1.label': 'Adventure Tours',
    'service.macera-turlari.stat1.value': '150+',
    'service.macera-turlari.stat2.label': 'Activity Types',
    'service.macera-turlari.stat2.value': '20+',
    'service.macera-turlari.stat3.label': 'Safety Score',
    'service.macera-turlari.stat3.value': '100%',
    'service.macera-turlari.stat4.label': 'Repeat Visits',
    'service.macera-turlari.stat4.value': '85%',
    'service.macera-turlari.category': 'Adventure Tours',

    // Tour Detail Page
    'tour-detail.breadcrumb.tours': 'Tours',
    'tour-detail.tour-duration': 'Tour Duration',
    'tour-detail.season': 'Season',
    'tour-detail.features-title': 'Tour Features',
    'tour-detail.info-title': 'Tour Information',
    'tour-detail.location': 'Location',
    'tour-detail.tour-organizer': 'Tour Organizer',
    'tour-detail.guide': 'Guide',
    'tour-detail.partner': 'Partner',
    'tour-detail.cta.title': 'Want a Similar Tour?',
    'tour-detail.cta.description': 'Contact us for an experience similar to this tour.',
    'tour-detail.cta.button': 'Contact Us',
    'tour-detail.other-tours.title': 'Our Other Tours',
    'tour-detail.other-tours.description': 'Discover other popular tours in our portfolio.',
    'tour-detail.other-tours.button': 'View All Tours',
    'tour-detail.meta.not-found': 'Tour Not Found | Parla Travel',

    // About Page
    // About Hero Section
    'about.hero.title.turkey': 'Discover',
    'about.hero.title.discovery': 'Turkey\'s',
    'about.hero.title.invite': 'Beauty',
    'about.hero.description': 'We are a professional team providing unforgettable experiences in cultural tourism, guidance and hotel reservation services for 15+ years.',
    'about.hero.cta.story': 'Discover Our Story',
    'about.hero.cta.video': 'Promotional Video',
    'about.hero.stats.guests': 'Happy Guests',
    'about.hero.stats.experience': 'Years Experience',
    'about.hero.stats.tours': 'Tours Completed',
    'about.hero.badge.experience': '15+ Years Experience',
    'about.hero.video.title': 'Parla Travel Promotional Video',
    'about.hero.alt.turkey': 'Beautiful Turkey Landscape',
    'about.hero.alt.istanbul': 'Istanbul Tourism',
    'about.hero.alt.culture': 'Turkish Culture',
    'about.hero.alt.travel': 'Travel Experience',
    'about.hero.alt.destinations': 'Beautiful Destinations',

    // Company Story Section
    'about.story.title': 'Our Story',
    'about.story.description': 'A journey leading Turkish tourism since 2008. We have grown with a focus on quality, trust and guest satisfaction at every step.',
    'about.story.foundation.year': '2008',
    'about.story.foundation.title': 'The Beginning of Our Tourism Journey',
    'about.story.foundation.description': 'We took our first steps in professional tourism guidance in Istanbul. Our vision was to introduce Turkey\'s cultural riches to the world and create unforgettable travel experiences.',
    'about.story.foundation.stat1.label': 'First Tour',
    'about.story.foundation.stat1.value': 'Istanbul',
    'about.story.foundation.stat2.label': 'Team Size',
    'about.story.foundation.stat2.value': '5 People',
    'about.story.expansion.year': '2015',
    'about.story.expansion.title': 'Service Diversity',
    'about.story.expansion.description': 'We expanded our team and added hotel reservations and cultural tours to our service portfolio. We started providing guidance services throughout Turkey.',
    'about.story.expansion.stat1.label': 'Tour Destinations',
    'about.story.expansion.stat1.value': '25+',
    'about.story.expansion.stat2.label': 'Team Size',
    'about.story.expansion.stat2.value': '20 People',
    'about.story.innovation.year': '2020',
    'about.story.innovation.title': 'Digital Transformation',
    'about.story.innovation.description': 'We embraced digital technologies, digitized customer experience by developing online booking system and mobile guidance applications.',
    'about.story.innovation.stat1.label': 'Online Bookings',
    'about.story.innovation.stat1.value': '85%',
    'about.story.innovation.stat2.label': 'Mobile App Downloads',
    'about.story.innovation.stat2.value': '10K+',
    'about.story.leadership.year': '2024',
    'about.story.leadership.title': 'Leading in Tourism Industry',
    'about.story.leadership.description': 'Today we are one of the most trusted brands in Turkish tourism and continue to shape the future travel experiences with our sustainable tourism approach.',
    'about.story.leadership.stat1.label': 'Annual Guests',
    'about.story.leadership.stat1.value': '5000+',
    'about.story.leadership.stat2.label': 'Team Size',
    'about.story.leadership.stat2.value': '45 People',
    'about.story.mission.title': 'Our Mission',
    'about.story.mission.description': 'To provide unforgettable travel experiences by introducing Turkey\'s unique beauties, rich culture and history to the whole world. In every tour, we embrace the principles of quality, trust and professionalism, and turn our guests\' dream vacation into reality.',

    // Company Values Section
    'about.values.title': 'Our Values',
    'about.values.description': 'As Parla Travel, our core values that guide us in every tour are the principles that make us different in the tourism sector and earn the trust of our guests.',
    'about.values.quality.title': 'Quality Service',
    'about.values.quality.description': 'We provide the highest service quality in every tour and prioritize the satisfaction of our guests.',
    'about.values.trust.title': 'Reliability',
    'about.values.trust.description': 'We establish long-term trust relationships with our guests and provide the experience we promised completely.',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.description': 'We follow tourism trends and improve travel experiences with technology-supported solutions.',
    'about.values.teamwork.title': 'Team Spirit',
    'about.values.teamwork.description': 'We work with our professional team and create unforgettable memories together.',
    'about.values.sustainability.title': 'Sustainable Tourism',
    'about.values.sustainability.description': 'With our environmentally friendly tourism approach, we protect local cultures and leave a livable world for future generations.',
    'about.values.passion.title': 'Passion and Dedication',
    'about.values.passion.description': 'We do tourism business with passion and put our hearts into every trip.',
    'about.values.culture.title': 'Our Corporate Culture',
    'about.values.culture.description': 'At Parla Travel, every individual is valuable. With our culture focused on open communication, continuous learning and development, we bring out the potential of our team members to the highest level. We grow together, we succeed together.',
    'about.values.culture.stat1.value': '45+',
    'about.values.culture.stat1.label': 'Team Members',
    'about.values.culture.stat2.value': '98%',
    'about.values.culture.stat2.label': 'Guest Satisfaction',
    'about.values.culture.stat3.value': '7.5',
    'about.values.culture.stat3.label': 'Average Working Duration (Years)',

    // Company Stats Section
    'about.stats.title.main': 'Parla Travel',
    'about.stats.title.highlight': 'in Numbers',
    'about.stats.description': 'We are a strong team leading Turkish tourism with our 15+ years of experience and achievements.',
    'about.stats.cultural.value': '220',
    'about.stats.cultural.label': 'Cultural Tours',
    'about.stats.special.value': '180',
    'about.stats.special.label': 'Special Tours',
    'about.stats.guide.value': '150',
    'about.stats.guide.label': 'Guide Services',
    'about.stats.suffix.tours': 'Tours',
    'about.stats.conclusion': 'In every tour, we combine quality, trust and professionalism to make our customers\' travel dreams come true and create unforgettable memories.',

    // About Page Metadata
    'about.meta.title': 'About Us | Parla Travel - 15+ Years Experience',
    'about.meta.description': 'As Parla Travel, we have been organizing pioneering tours in tourism, cultural tours and guide services for 15+ years. Meet our company story and values.',
    'about.meta.keywords': 'about parla travel, tourism company, cultural tours, guide services, company history',
    'about.meta.og.title': 'About Us | Parla Travel',
    'about.meta.og.description': 'As Parla Travel, we have been organizing pioneering tours in tourism, cultural tours and guide services for 15+ years.',

    // Blog Detail Page
    'blog-detail.breadcrumb.blog': 'Blog',
    'blog-detail.share.title': 'Share This Article',
    'blog-detail.share.button': 'Share',
    'blog-detail.author.label': 'Author',
    'blog-detail.author.title': 'Parla Travel Expert',
    'blog-detail.related.title': 'Related Articles',
    'blog-detail.related.description': 'Discover our other articles related to this topic.',
    'blog-detail.related.view-all': 'View All Blog Posts',

    // Blog Newsletter
    'blog-detail.newsletter.title': 'Don\'t Miss Blog Updates',
    'blog-detail.newsletter.subtitle': 'Blog Updates',
    'blog-detail.newsletter.description': 'We send the latest destinations, guide recommendations and special tour opportunities to your email address,',
    'blog-detail.newsletter.description.highlight': 'making you a pioneer in discovery',
    'blog-detail.newsletter.form.title': 'Newsletter',
    'blog-detail.newsletter.form.subtitle': 'Weekly updates',
    'blog-detail.newsletter.form.email.label': 'Your Email Address',
    'blog-detail.newsletter.form.email.placeholder': 'example@email.com',
    'blog-detail.newsletter.form.name.label': 'Your Name (Optional)',
    'blog-detail.newsletter.form.name.placeholder': 'Your Full Name',
    'blog-detail.newsletter.form.consent': 'I accept the processing of my personal data within the scope of GDPR and receiving email updates.',
    'blog-detail.newsletter.form.submit': 'Subscribe to Newsletter',
    'blog-detail.newsletter.benefits.title': 'What Will You Gain?',
    'blog-detail.newsletter.benefits.priority.title': 'Priority Information',
    'blog-detail.newsletter.benefits.priority.description': 'Be the first to hear about new destination guides and special tour opportunities.',
    'blog-detail.newsletter.benefits.analysis.title': 'Destination Analysis',
    'blog-detail.newsletter.benefits.analysis.description': 'Detailed destination guides and travel recommendations.',
    'blog-detail.newsletter.benefits.offers.title': 'Special Tour Opportunities',
    'blog-detail.newsletter.benefits.offers.description': 'Exclusive tour discounts and early booking opportunities for subscribers only.',
    'blog-detail.newsletter.stats.subscribers': 'Active Subscribers',
    'blog-detail.newsletter.stats.satisfaction': 'Satisfaction Rate',

    // Blog Detail Metadata
    'blog-detail.meta.not-found': 'Blog Post Not Found | Parla Travel',
    'blog-detail.meta.blog-suffix': '| Parla Travel Blog',
    
    // Service Detail Metadata
    'service-detail.meta.not-found': 'Service Not Found | Parla Travel',
    'service-detail.meta.description': 'Experience unforgettable travel adventures in Turkey\'s most beautiful destinations.',
    'service-detail.meta.culture-tours': 'Cultural Tours',
    'service-detail.meta.hotel-reservation': 'Hotel Reservation',
    'service-detail.meta.guide-services': 'Professional Guide Services',
    'service-detail.meta.adventure-tours': 'Adventure Tours'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}